### ISSUE TITLE
`mexico_sinaloa_ceaip` is no longer available (2023-10)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1031]
http://ceaipsinaloa.ddns.net:4000/contratacionesabiertas returns address unreachable

**Comment by jpmckinney** [comment]
Same with http://ceaipsinaloa.ddns.net:3000

http://ceaipsinaloa.ddns.net returns a login page (separate application)

**Comment by yolile** [comment]
Now the API is working but it returns empty results or 404.
The site itself contains no data
![image](https://github.com/open-contracting/kingfisher-collect/assets/6834122/107765a9-84de-4297-8adc-2b01a572b4b7)
