### ISSUE TITLE
chile_compra_api_records/chile_compra_api_releases return 502

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#1037]
e.g. https://open-contracting-partnership.sentry.io/issues/2631582176/?project=5287294&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

Not sure what proportion of requests time out.

**Comment by jpmckinney** [comment]
Can filter Sentry with `!message:"Error downloading <GET http://api.mercadopublico.cl/APISOCDS/OCDS/listaOCDSAgnoMes*"` The URLs also fail for me locally, e.g. http://api.mercadopublico.cl/APISOCDS/OCDS/listaOCDSAgnoMesConvenio/2022/07/0/10

**Comment by yolile** [comment]
The requests are now working but they are returning 502 when requesting them from scrapy (either locally or from the server). They work via the browser or with curl (locally and on the server).

**Comment by jpmckinney** [comment]
Where are the docs? The Swagger URL in the spider is 404: https://desarrolladores.mercadopublico.cl/docs/services/5a9ed02f718ed712f4403e75/operations/data-listaa-omes-agno-mes

desarrolladores.mercadopublico.cl doesn't respond.

api.mercadopublico.cl has no OCDS docs that I can find.

**Comment by yolile** [comment]
The new API documentation is available at https://datos-abiertos.chilecompra.cl/descargas/procesos-ocds

**Comment by jpmckinney** [comment]
Do they still respond with e.g. `{"status": 500, "detail": "error"}` according to the docs? `status` used to be in every response, but it's no longer there.

**Comment by jpmckinney** [comment]
Fixed in 0a886628 (had to use https not http). I deleted parse_list_loader, since `status` isn't set (at least not for successful responses – no idea what happens with error responses).

**Comment by yolile** [comment]
> Do they still respond with e.g. {"status": 500, "detail": "error"} according to the docs? 

Hard to test and the spider is not working, but at least for 502 they respond with the actual 502 error

**Comment by yolile** [comment]
> Fixed in https://github.com/open-contracting/kingfisher-collect/commit/0a886628b7235545a0ab19ff94b5323057c91bf9 (had to use https not HTTP)

Cool, thanks, I only tried setting the browser user agent and similar

**Comment by jpmckinney** [comment]
Job automatically started, so we'll see what errors occur, if any.
