### ISSUE TITLE
Albania

### ISSUE THREAD

**Issue by allakulov** [open-contracting/kingfisher-collect#1040]
**Links to bulk download and/or API documentation**
https://kpp.al/en/Historiku?nrVendimi=&OperatoriEkonmik=&idOperatori=&autoritetiKotraktues=&id=

**Links to bulk download and/or API endpoints**
https://kpp.al/en/Historiku?nrVendimi=&OperatoriEkonmik=&idOperatori=&autoritetiKotraktues=&id=

**Priority**
anytime

**Data structure**
Seem to be valid OCDS data, reviewable using the DRT

**Publication format**
Release packages published by year in JSON format.

**Comment by yolile** [comment]
@allakulov added and deployed. Note that the spider has to extract the release package from a "result" object.
