### ISSUE TITLE
Mendoza Province (Argentina)

### ISSUE THREAD

**Issue by fppenna** [open-contracting/kingfisher-collect#1042]
**Links to bulk download and/or API documentation**
https://datosabiertos-compras.mendoza.gov.ar/datasets/

**Links to bulk download and/or API endpoints**
https://datosabiertos-compras.mendoza.gov.ar/descargar-json/2020_20231021_v1_release.json
https://datosabiertos-compras.mendoza.gov.ar/datosabiertos/

**Priority**
anytime

**Comment by yolile** [comment]
@fppenna the API endpoints return empty packages, e.g. https://datosabiertos-compras.mendoza.gov.ar/getRelease/2023/metodo/selective
https://datosabiertos-compras.mendoza.gov.ar/getRelease/2023/metodo/open

So I only created `argentina_mendoza_province_bulk` for now. We can create a new issue if they fix their API.
