### ISSUE TITLE
dominican_republic_api: Incorrect id and date, and tenderers is sometimes an object

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#1049]
For example: ocid `ocds-6550wx-TESORERIA NACIONAL-DAF-CM-2022-0062` has a release where `bids.details` is:

```json
[
  {
    "id": "DO1.RPL.3330807",
    "date": "2022-12-08 15:45:47.8730413",
    "value": {
      "amount": 196000.006
    },
    "status": "Qualified",
    "tenderers": {
      "id": 86075,
      "name": "Transolucion JR, SRL"
    }
  },
  {
    "id": "DO1.RPL.3342770",
    "date": "2022-12-19 16:00:00.0000000",
    "value": {
      "amount": 179334.001829
    },
    "status": "Qualified",
    "tenderers": {
      "id": 235,
      "name": "Santo Domingo Motors Company, SA"
    }
  },
  {
    "id": "DO1.RPL.3331110",
    "date": "2022-12-08 16:41:41.5945438",
    "value": {
      "amount": 221840
    },
    "status": "Qualified",
    "tenderers": {
      "id": 87229,
      "name": "RIF Investment Group, SRL"
    }
  }
]
```

----

Another issue: All the releases have the same id `TESORERIA NACIONAL-DAF-CM-2022-0062-1` and date `2022-12-07T18:00:34Z`. I don't know if this issue is universal or not.

Having the same date means releases can't be reliably ordered, such that the compiled release can be incorrect. (The other fields in the releases are not identical.)

**Comment by jpmckinney** [comment]
In Kingfisher Process, I'll now handle OCDS Merge errors (i.e. just skip that OCID). It'll log the exception to Sentry and add a note to the collection_note table.

**Comment by jpmckinney** [comment]
The `tenderers` issue seems to occur 110 times: https://open-contracting-partnership.sentry.io/issues/4905536293/

**Comment by yolile** [comment]
@jpmckinney are you logging this here because you expect we resolve this in Collect or only because we don't have a better place to track this?

**Comment by jpmckinney** [comment]
I usually log issues, and then think of the solutions later.

In this case, I don't think there is anything to do in Collect. I made the necessary change in Process, and I'll open an issue OCDS Merge (or Process) about warning about equal dates.

**Comment by jpmckinney** [comment]
So, we can close this issue here.

**Comment by yolile** [comment]
> I usually log issues, and then think of the solutions later.

Sounds good, I was just wondering if the issue belongs here or if, in general, we should have a better place to report this type of issue (I'm thinking about the "Data quality" section of the publication in the Registry, for example, e.g. comment on the descriptions document and tag me + the data lead for that publisher so that we can do both, update the registry and let the partner know)

**Comment by jpmckinney** [comment]
Just a note that Kingfisher Process does NOT have a unique index on collection, ocid, release_id, and so the repetition of the release IDs will not cause any loss of data at that level.

**Comment by jpmckinney** [comment]
I created the follow-up issue (not prioritized), so this issue can now be closed.

https://github.com/open-contracting/ocds-merge/issues/37
