### ISSUE TITLE
dominican_republic_api: implement from and until date with new endpoint

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1051]
Now they have https://api.dgcp.gob.do/api/docs/#/Release/get_api_date__date1___date2___page_, e.g. https://api.dgcp.gob.do/api/date/2023-01-01/2023-01-13/1

where we can query by a start and end date,  yyyy-mm-dd format.

**Comment by jpmckinney** [comment]
Awesome. Once done, a reminder to check if the incremental crawl command needs any updates.

**Comment by yolile** [comment]
Yeap, was about to create an issue in the deploy repo, but it seems we won't need to change anything!

**Comment by yolile** [comment]
Well, maybe the one thing we could try now is to increase the update frequency

**Comment by jpmckinney** [comment]
Yeah, ideally daily – and if so, that'll motivate me to do https://github.com/open-contracting/deploy/issues/450
