### ISSUE TITLE
Add CDL Assam spider

### ISSUE THREAD

**Issue by ndrhzn** [open-contracting/kingfisher-collect#1060]
While CDL presents OCDS data at https://assam.open-contracting.in/datasets, actual datasets (OCDS package & flattened data) are stored on GitHub

**Links to bulk download and/or API documentation**
https://github.com/CivicDataLab/assam-tenders-data/tree/main/data

**Links to bulk download and/or API endpoints**
https://github.com/CivicDataLab/assam-tenders-data/blob/main/data/ProcessedData/ocds-mapped-data/current/ocds_mapped_data.json.zip

**Priority**
anytime

**Data structure**
Data has been checked using DRT (and DRT was able to process it)

**Publication format**
Data is provided as an archive that contains package.json file with compiled releases packaged.

**Comment by yolile** [comment]
@ndrhzn do they share the link to the GitHub repo somewhere in their website? The only other link I could find in their website was one to a Google Drive file:
![image](https://github.com/open-contracting/kingfisher-collect/assets/6834122/f5bc6182-872a-419f-8b3c-24a823c069a2)

**Comment by yolile** [comment]
Never mind, I see now that the Download button redirects to the GitHub file 👍🏻

**Comment by yolile** [comment]
@ndrhzn deployed, see https://kingfisher-collect.readthedocs.io/en/latest/spiders.html#kingfisher_scrapy.spiders.india_assam_civic_data_lab.IndiaAssamCivicDataLab
