### ISSUE TITLE
honduras_portal_api_* returns 502 error for deep pages (2024-04)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1079]
e.g. https://www.contratacionesabiertas.gob.hn/api/v1/release/?format=json&page=5000

**Comment by yolile** [comment]
Note that the endpoint doesn't provide any filters so we can't save this by forcing date filters

**Comment by jpmckinney** [comment]
Do we actually use this spider? The only honduras_portal_* I found is the bulk one, and that one is "no longer updated by the publisher": https://data.open-contracting.org/admin/data_registry/collection/26/change/?_changelist_filters=q%3Dhonduras
