### ISSUE TITLE
New spider for Rwanda: Public Procurement Authority (RPPA)

### ISSUE THREAD

**Issue by allakulov** [open-contracting/kingfisher-collect#1091]
**Links to bulk download and/or API documentation**
https://ocds.umucyo.gov.rw/core/api/docs

**Links to bulk download and/or API endpoints**
https://197.243.26.63/core/api/docs#/Releases/get_release_api_v1_releases_all_get

**Priority**
As soon as possible

**Data structure**
Previous data samples were structurally valid and possible to review with the DTR

**Publication format**
Release package

**Comment by yolile** [comment]
Deployed, and a crawl started (see logs [here](https://collect.kingfisher.open-contracting.org/logs/kingfisher/rwanda/912d67e42ce611efa96b25eb3966e524.log)). Note that it seems to be data since 2016-07-13
