### ISSUE TITLE
spain_zaragoza: their entire site is down (2024-08)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1097]
e.g https://www.zaragoza.es is not responding

https://www.zaragoza.es/sede/servicio/contratacion-publica/ocds/contracting-process/?rf=html&rows=100000

**Comment by jpmckinney** [comment]
Already frozen in registry

**Comment by yolile** [comment]
It is working again now

**Comment by yolile** [comment]
Hmm https://www.zaragoza.es/sede/servicio/contratacion-publica/ocds/contracting-process/?rf=html&rows=100000 works from the browser but not from collect or curl (error 500)

**Comment by yolile** [comment]
The say they now have an API v2 so we probably need to update the spider https://www.zaragoza.es/sede/portal/datos-abiertos/api

**Comment by jpmckinney** [comment]
Fixed by setting user agent. I'll open new issue about new API.
