### ISSUE TITLE
mexico_nuevo_leon_releases: update endpoints

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#1100]
https://smpu.nl.gob.mx/acceso/DatosAbiertos/JSONsInfraestructuraAbierta.rar linked from https://smpu.nl.gob.mx/transparencia/acerca-del-proyecto requires HTTP authentication (no login provided, as far as I can see).

**Comment by yolile** [comment]
For records, they have now this endpoint:

https://smpu.nl.gob.mx/siasi_ws/api/ocds/ListarRecordPackagesXAnio?anio=[{"value":"2023"}]

**Comment by yolile** [comment]
They also have
https://smpu.nl.gob.mx/siasi_ws/api/ocds/ListarProduccionXAnio?anio=[{"value":"2023"}]
