### ISSUE TITLE
Obras Públicas Chile (Observatorio del Gasto Fiscal - Dirección General de Obras Públicas)

### ISSUE THREAD

**Issue by fppenna** [open-contracting/kingfisher-collect#1103]
**Links to bulk download documentation**
https://obrapublica.cl/Data/

**Links to bulk download endpoints**
https://obrapublica.cl/download/ocds_descargamasiva.zip

**Priority**
anytime

**Data structure**
The data is structurally valid against OCDS 

**Publication format**
A zip file containing multiple record packages. Each record package includes a single record, with the package metadata located at the top level of the JSON file

**Comment by yolile** [comment]
Implemented and deployed, spider name: chile_public_works_bulk
