### ISSUE TITLE
nigeria_portal: Response indefinitely slow (2024-10)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#1116]
https://nocopo.bpp.gov.ng/ocdsjson.ashx?ocid=all

**Comment by jpmckinney** [comment]
Seems responsive now (note that the above URL has a meta refresh which is followed – test that URL).

**Comment by jpmckinney** [comment]
https://nocopo.bpp.gov.ng/ocdsjson.ashx?ocid=all now 503s. I'll leave as-is since it worked 2 days ago.

**Comment by yolile** [comment]
Edit: it seems it works if you wait enough so that I will increase the download time in the spider
