### ISSUE TITLE
Nuevo León: Secretaría de Administración (Mexico)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#1124]
**Links to bulk download and/or API documentation**
https://catalogodatos.nl.gob.mx/dataset/contrataciones-abiertas-direccion-general-de-adquisiciones-y-servicios

**Links to bulk download and/or API endpoints**
https://catalogodatos.nl.gob.mx/dataset/contrataciones-abiertas-direccion-general-de-adquisiciones-y-servicios

**Priority**
as soon as possible

**Data structure**
Not checked

**Publication format**
Not checked

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*

cc @fppenna

**Comment by jpmckinney** [comment]
> Source mexico_nuevo_leon_infra_abierta_records yields an unknown or unsupported format, skipping

> UnknownFormatError: top-level JSON value is a non-OCDS array

Also the filenames look incorrectly formatted:

> anio-[{"value":"2024"}].json

**Comment by yolile** [comment]
Ah, wrong issue, this issue was for adding the `mexico_nuevo_leon` spider
