### ISSUE TITLE
Honduras: Add spider argument to filter ONCAE and SEFIN

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#125]
See unmerged commit on a branch on the old repo: https://github.com/open-contracting/kingfisher/commit/ab1ac7a2012be5f367a5f11612f3ce89c31daa66

**Comment by jpmckinney** [comment]
cc @yolile

**Comment by yolile** [comment]
That scraper was made using a test url that is no longer available. When the data will be in production we can change the url and make the PR

**Comment by jpmckinney** [comment]
Thanks – I added the "blocked" label.

**Comment by jpmckinney** [comment]
Closing until publication is available.

**Comment by romifz** [comment]
Hi James, the data from SEFIN is available through the `honduras_portal_releases`, `honduras_portal_records`, and `honduras_portal_bulk_files` scrapers.

If we want to get the data from SEFIN only, I believe we can modify the scrapers to accept a `publisher` parameter. According to the [API documentation](http://www.contratacionesabiertas.gob.hn/manual_api/) the releases endpoint accepts a similar parameter, which values can be "oncae" or "sefin". For the bulk files' version, the scraper retrieves a JSON document with the information of each compressed file, including the publisher, so we can filter the files available.

**Comment by jpmckinney** [comment]
Thanks! I've updated the issue description.
