### ISSUE TITLE
Improve documentation on reading log files

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-collect#198]
From @pindec 

It would be helpful for analysts to have a guide to interpreting scrapy summary stats to help them understand whether a scrape has malfunctioned and inform issue reporting.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [kingfisher-scrape - document how to interpret scrapy summary stats](https://trello.com/c/Rsn2HF6v/115-kingfisher-scrape-document-how-to-interpret-scrapy-summary-stats)

**Comment by odscjames** [comment]
@pindec @mrshll1001 @duncandewhurst (+ Analysts)

I have started https://github.com/open-contracting/kingfisher-scrape/pull/220/ - can you check that, is that the kind of thing that is helpful?

After that it would be good to have a chat to Analysts about what else would be good.

**Comment by odscjames** [comment]
This is now at https://kingfisher-scrape.readthedocs.io/en/latest/run-report-guide.html

**Comment by jpmckinney** [comment]
@pindec Was the problem you were experiencing that a spider wouldn't behave as expected, for any reason (e.g. it encountered an error and stopped mid-way, some URLs weren't retrieved but it continued, it only traversed a tenth of the dataset and then considered itself to be done, etc.)? Or was the problem very specific?

The [crawl report guide](https://kingfisher-scrape.readthedocs.io/en/latest/crawl-report-guide.html) deals with interpreting Scrapy statistics… but these exclude the exceptions and error messages that immediately follow the Scrapy statistics in the full log file. If this documentation is meant to address the full range of errors that can occur, then the summary reports (and the documentation) are lacking important information.

**Comment by pindec** [comment]
@jpmckinney The former - as part of the data review process, analysts need to access/understand the scrapy logs as part of trying to determine whether the 'correct' number of releases/records end up in Kingfisher. 

For that, we need to understand whether a spider has not behaved as expected for any reason, and have information to help determine the correct course of action (e.g. re-run scraper, or open an issue).

For very large logs, having the end-summary extracted to a separate location is also helpful to avoid waiting for the full log file to load.

Exposing the full range of errors that can occur would be helpful.

**Comment by jpmckinney** [comment]
Making a few notes of different log events to incorporate into documentation. Also, instead of investing any time in parsing logs, we should just use https://github.com/my8100/logparser

* Log file ends with finished status

```
2020-01-22 21:44:52 [scrapy.core.engine] INFO: Spider closed (finished)
```

* Log file ends with exception and traceback

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.contrataciones.gov.py', port=443): Max retries exceeded with url: /datos/api/v2/oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe0f49aa6d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

```
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.contrataciones.gov.py', port=443): Max retries exceeded with url: /datos/api/v2/oauth/token (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2697107e48>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)))
```

**Comment by jpmckinney** [comment]
Other useful stats that don't always occur, but that indicate error conditions (found by grep'ing Scrapy code for `stats\.`):

* downloader/exception_count
* downloader/exception_type_count
* scheduler/unserializable
* spider_exceptions/%s
* retry/max_reached

Also good to check that `finish_reason` is 'finished' and not something else.

We set `HTTPERROR_ALLOW_ALL` so 'httperror/response_ignored_count' should never occur.

**Comment by jpmckinney** [comment]
Before #266, the digiwhist_poland log would include:

```
2020-02-18 14:59:47 [scrapy.core.downloader.handlers.http11] ERROR: Cancelling download of https://opentender.eu/data/files/PL_ocds_data.json.tar.gz: expected response size (2558889896) larger than download max size (1073741824).
2020-02-18 14:59:47 [scrapy.core.scraper] ERROR: Error downloading <GET https://opentender.eu/data/files/PL_ocds_data.json.tar.gz>
Traceback (most recent call last):
  File "/Users/james/.pyenv/versions/3.6.1/envs/ocdskingfisherscrape/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/Users/james/.pyenv/versions/3.6.1/envs/ocdskingfisherscrape/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/Users/james/.pyenv/versions/3.6.1/envs/ocdskingfisherscrape/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 44, in process_request
    defer.returnValue((yield download_func(request=request, spider=spider)))
  File "/Users/james/.pyenv/versions/3.6.1/envs/ocdskingfisherscrape/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/james/.pyenv/versions/3.6.1/envs/ocdskingfisherscrape/lib/python3.6/site-packages/scrapy/core/downloader/handlers/http11.py", line 388, in _cb_bodyready
    raise defer.CancelledError(error_msg % error_args)
twisted.internet.defer.CancelledError: Cancelling download of https://opentender.eu/data/files/PL_ocds_data.json.tar.gz: expected response size (2558889896) larger than download max size (1073741824).
2020-02-18 14:59:47 [scrapy.core.engine] INFO: Closing spider (finished)
```

The statistics included:

```
{'downloader/exception_count': 1,
 'downloader/exception_type_count/twisted.internet.defer.CancelledError': 1,
 …
 'log_count/ERROR': 2,
```

However, the `finish_reason` was still 'finished'.
