### ISSUE TITLE
Rename to Kingfisher Collect

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#228]
Not a priority, but before we promote the tool more significantly, we should consider renaming it.

I remember [a user](https://crm.open-contracting.org/issues/4814#note-4) who didn't consider it to be what they were looking for, because they didn't want a tool that parsed data out of HTML content (which is error prone), but instead wanted a tool that read from OCDS APIs.

Similarly, the documentation should refer to spiders and crawls (like Scrapy does) rather than scrapers and scrapes (if there are any such instances).

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Scrape to Collect](https://trello.com/c/Yhq0lctw/178-rename-scrape-to-collect)

**Comment by robredpath** [comment]
Yup, I like the idea of moving away from calling it "Scrape" for exactly the reasons you outline. 

I also like the idea of updating the documentation to use the language that the underlying tools do, to avoid ambiguity. If at some point we were to move away from using Scrapy, the docs would have to be extensively rewritten and so there's little to be gained from having more generic language there. I've added https://github.com/open-contracting/kingfisher-scrape/issues/247 as I think the work's sufficiently distinct, and doesn't require agreement on a name(!)
