### ISSUE TITLE
Handle spider_closed signal, if reason is 'cancelled' or 'shutdown'

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#278]
Right now, we only send a request to Kingfisher Process when the reason is 'finished' (i.e. the crawl completed successfully). If scrapyd was stopped, or if the spider was closed for any other reason, then no request is sent to Kingfisher Process – leaving the collection open forever.

We should agree what the appropriate behavior should be.

We can change the Kingfisher Process `end_collection_store/` endpoint to accept an additional 'reason' parameter, so that we can close the collection, and include the reason for its closure. We would just need to indicate to analysts (or instruct analysts to check) the reason for its closure.

**Comment by jpmckinney** [comment]
What do you think @pindec @romifz @yolile @aguilerapy @duncandewhurst @mrshll1001 ?

**Comment by romifz** [comment]
That sounds good for me. I think it would also help to have that information in the collections table to identify collections that are potentially incomplete.

**Comment by duncandewhurst** [comment]
+1 to what @romifz said.

At the moment when we are troubleshooting kingfisher issues, we interpret collections with a value in `collection.store_end_at` as having successfully completed the scrape stage.

**Comment by yolile** [comment]
> We can change the Kingfisher Process end_collection_store/ endpoint

@jpmckinney shouldn't we wait for this to be done before changing kingfisher collect?

**Comment by jpmckinney** [comment]
Done in #745. The reason is sent to Kingfisher Process, which stores it as a collection note.
