### ISSUE TITLE
Use Twisted for Kingfisher Process API requests

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#292]
Presently, we add a new dependency (`requests`) to make requests in `kingfisher_process.py`. But, Scrapy is already built on Twisted. We should use that instead.

*(Deleted long, old proposal, to avoid confusion)*

**Comment by jpmckinney** [comment]
Once this and #293 are done, we can remove `requests` as a dependency (also requires updates to documentation).

**Comment by jpmckinney** [comment]
With Scrapy 2, it might be possible to write shorter / cleaner code: https://docs.scrapy.org/en/latest/topics/coroutines.html

**Comment by jpmckinney** [comment]
Not sure if perhaps we can use `spider.crawler.engine.download` like in this example: https://docs.scrapy.org/en/latest/topics/item-pipeline.html#take-screenshot-of-item

I think extensions can also return Deferred's, in case that can be useful.

**Comment by jpmckinney** [comment]
Aha! Some Scrapy examples use [treq](https://github.com/twisted/treq), which has a requests-like API, but uses Twisted.

**Comment by jpmckinney** [comment]
We can use `await` with treq, so that the KFP request doesn't block: https://docs.scrapy.org/en/latest/topics/coroutines.html

**Comment by jpmckinney** [comment]
* treq doesn't support proxies (which is fine: we disabled them for requests): https://treq.readthedocs.io/en/release-20.9.0/#feature-parity-with-requests
* Its `_convert_files` method requires a different order to `files` tuples: https://treq.readthedocs.io/en/release-20.9.0/_modules/treq/client.html?highlight=_convert_files

**Comment by yolile** [comment]
- Its `_converted` method supports only: tuples, lists, bytes or text parameters (not booleans eg sample=true): https://treq.readthedocs.io/en/release-20.9.0/_modules/treq/multipart.html?highlight=_converted

**Comment by yolile** [comment]
closed by #559
