### ISSUE TITLE
Remove *.fileinfo files

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#307]
These files store the URL, data type (e.g. 'release_package') and encoding. I assume they exist so that if the files are restored from a backup, it'd be possible to (1) load them into Kingfisher Process (using the data type) and (2) know their provenance (using the URL). I don't know what the encoding is useful for.

For the django branch of Kingfisher Process, the load command will use OCDS Kit's ability to [auto-detect](https://ocdskit.readthedocs.io/en/latest/cli/ocds.html#detect-format) the format of files. (We can also consider auto-detecting the encoding, though to my knowledge Kingfisher Scrape saves files as UTF-8, and the encoding in the fileinfo file is the original encoding.)

Once that branch is live, the only reasons to store these fileinfo files will be (1) the data type is not detectable (i.e. the OCDS data is embedded deep in the JSON, though this should occur rarely and should be easy to determine from the spider's code) and (2) to know the provenance.

However, **do we care about the specific provenance of each file?** To my knowledge, the data source and collection time are the only relevant details in terms of provenance.

**Comment by yolile** [comment]
I think that to load an old directory to the database we can always use the Kingfisher Process's local load feature. To know the data_type we can always check the code. And I don't think the source URL of each file is relevant. With that said, I prefer to not store the .fileinfo files, as this is especially a problem for big sources like Colombia or Paraguay.

**Comment by yolile** [comment]
@duncandewhurst @mrshll1001 @romifz what do you think?

**Comment by romifz** [comment]
Personally, I never had the need to use the *.fileinfo files. 

I guess the URL could be relevant in the case that a file served by the publisher is corrupt or not valid JSON, so we can inform the publisher. This never happened to me, and I guess in that case we would see the URL in the spider log anyways?

**Comment by jpmckinney** [comment]
> I guess the URL could be relevant in the case that a file served by the publisher is corrupt or not valid JSON, so we can inform the publisher. This never happened to me, and I guess in that case we would see the URL in the spider log anyways?

Yes, all URL requests are logged, and there's a separate issue about backing up or archiving logs for older collections.

**Comment by duncandewhurst** [comment]
I also haven't used the *.fileinfo files, so I'm happy for them to be removed.
