### ISSUE TITLE
Should filenames be meaningful?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#317]
Some spiders have meaningful filenames like `page1.json`, etc. Others use `hashlib.md5` to generate a unique filename based on a URL pattern and URL parameters.

My understanding is that, for each file, we:

1. Save the URL to a *.fileinfo file #307 
1. Send the URL to Kingfisher Process

As such, we can always directly determine the URL from which the file was fetched, without having to rely on the filename.

In that case, should we just be consistent and have all filenames be md5 hashes? Or, is there some value in having meaningful filenames? If so, should we only use md5 hashes for filenames in cases where we can't otherwise guarantee uniqueness?

**Comment by jpmckinney** [comment]
What do you think @pindec @romifz @yolile @aguilerapy @duncandewhurst @mrshll1001 ?

**Comment by romifz** [comment]
For our use of kingfisher-collect, I think there are no benefits in keeping the original file names. 

For someone else using kingfisher-collect to download data only, there may be a case to have the original file names. For example, Honduras ONCAE file names are meaningful (they contain the source system name and the year for the release date), and a user might download all files and pick a subset of the files to analyze. I'm not sure if we have similar cases with other publishers. I believe Honduras SEFIN will follow a similar approach to name their files but they are not publishing yet.
