### ISSUE TITLE
Another Moldova endpoint?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#333]
I've been looking into the Moldova implementation as part of preparing an implementation case study and noticed that the [updated version](https://opencontracting.eprocurement.systems) of the original open contracting portal includes a releases endpoint which includes data for 2019 and 2020, e.g. https://opencontracting.eprocurement.systems/ocds-api/year/2020

I checked the existing Moldova scrapers and it doesn't look like we're scraping this endpoint.

I loaded the data from 2019 into Kingfisher process (collection_id = 1079) and it looks like there is one release per contracting process, so this could be serving the purpose of bringing together the data from the different mTender endpoints under a single ocid, albeit with a limited set of fields. There is also exactly 5,000 releases, so we should check if there is pagination.

@jpmckinney @mrshll1001 any views on whether we should add a scraper for this endpoint?

**Comment by jpmckinney** [comment]
Can you ask Viktor about the endpoint via the CRM? I figure we should add it, but want to confirm where this endpoint came from.

**Comment by jpmckinney** [comment]
It seems like the question about https://opencontracting.eprocurement.systems/ocds-api/year/2020 was not answered in #5790

**Comment by duncandewhurst** [comment]
Unfortunately not, I can ask Paul and Viktor again?

**Comment by jpmckinney** [comment]
@duncandewhurst Yes, let's try once more.

**Comment by jpmckinney** [comment]
CRM-5790 was not updated. In any case, the URL now redirects to https://opencontracting.eprocurement.systems/login, so closing this issue.
