### ISSUE TITLE
Add docstrings to spider classes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#347]
Include:

* [x] API (or bulk download) documentation URL
* [x] List of spider arguments (e.g. Colombia has sample, year and page)
  * Since the sample argument doesn't do that exact same thing for all spiders, we should document what it does for each spider (example below).

For example (this will render as definition lists in Sphinx):

```rst
API documentation
  https://www.colombiacompra.gov.co/transparencia/api
Swagger API documentation
  https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/
Spider arguments
  sample
    Download only the first page of results.
  page
    The page number from which to start crawling.
  year
    The year to crawl. See API documentation for valid values.
```

While we're at it, we should rename Colombia's `start` to `start_page`.

Once we start, we can add Sphinx's `automodule` for these docstrings to be rendered in the documentation.

**Comment by jpmckinney** [comment]
@aguilerapy Thanks to your work in #350, we can now have nice docs like: https://kingfisher-scrape.readthedocs.io/en/latest/spiders.html#openopps, so that users can easily see what options each spider supports.

**Comment by aguilerapy** [comment]
With #389 and #393 we cover all the spiders availables except the digiwhist ones, we can close this or there is something else to do?

**Comment by jpmckinney** [comment]
I think that’s everything! Thanks!
