### ISSUE TITLE
digiwhist_poland: Timeout

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#348]
I tried these scrapers:

- [x] portugal
- [ ] digiwhist_poland
- [x] chile_compra_bulk

**Comment by jpmckinney** [comment]
Do you have links to logs or errors, etc.?

**Comment by jpmckinney** [comment]
At http://scrape.kingfisher.open-contracting.org/logs/kingfisher/portugal/94e9d76475de11ea96750c9d92c523cb.log I see:

> 2020-04-03 21:19:46 [portugal] WARNING: Failed to post [https://dados.gov.pt/s/resources/contratos-publicos-formato-ocds-informacao-registada-no-portal-base-em-www-base-gov-pt/20191128-111631/base2-pt-ocds-201911.zip]. API status code: 500

When I try digiwhist_poland locally I get:

> 2020-04-03 23:48:12 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://opentender.eu/data/files/PL_ocds_data.json.tar.gz> (failed 3 times): User timeout caused connection failure: Getting https://opentender.eu/data/files/PL_ocds_data.json.tar.gz took longer than 180.0 seconds..
> 2020-04-03 23:48:12 [scrapy.core.scraper] ERROR: Error downloading <GET https://opentender.eu/data/files/PL_ocds_data.json.tar.gz>

**Comment by romifz** [comment]
Portugal has a single big file (~500mb compressed, ~4gb flat) so I'm afraid that's an issue. I asked @aguilerapy to open an issue because last week I got no log files when running the Portugal scraper, but the issue seems to be gone now.

I'll open a separate issue for Portugal.

**Comment by aguilerapy** [comment]
Portugal scraper fixed in #357

**Comment by yolile** [comment]
closed by #635
