### ISSUE TITLE
paraguay_dncp_releases: Sends many file items with duplicate composite keys

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#355]
https://sentry.io/organizations/open-data-services/issues/1601860621/?project=1404981&query=is%3Aunresolved

For example:

> DatabaseStore class tried to insert a duplicate collection_file_item row! collection_file_id = 143072270 number = 0 existing row id = 202704392

cc @yolile

**Comment by yolile** [comment]
@jpmckinney could you provide more details on what is happening here? how the composite key is formed?

**Comment by jpmckinney** [comment]
@yolile The key is collection_file_id & number. (You can search the error message in Kingfisher Process' code to analyze.)

**Comment by yolile** [comment]
I cheked kingfisher process code and the error is raised in _enteder_ DatabaseStore class method, but it is hard to know when or why this method is called, also the error is kind of weird as collection_file_id and number are autogenerated columns if I dont understand it wrong. So not sure what can be happening. 
I checked the last paraguay_dncp collection and there is not duplicated releases (at least all the releases have different ids)

**Comment by jpmckinney** [comment]
Yeah, the rewrite will make this all simpler on the Process side. `__enter__` is called whenever `DatabaseStore` is used as a context manager (`with DatabaseStore …`).

In `paraguay_dncp_base`, why do we have `dont_filter=True` in `parse_pages`? If that results in yielding duplicates to Process, it will cause the error. We should only use `dont_filter` to do things like getting tokens, etc. Is `kf_filename` guaranteed to be unique?

**Comment by yolile** [comment]
> In paraguay_dncp_base, why do we have dont_filter=True in parse_pages?

@aguilerapy ?

> Is kf_filename guaranteed to be unique?

I use the release id as filename, so yes, it should be unique

**Comment by jpmckinney** [comment]
Are release IDs globally unique within DNCP's dataset, or only unique in the context of their OCID?

**Comment by yolile** [comment]
globally unique!

**Comment by jpmckinney** [comment]
Hmm, then my best guess is that there are duplicate requests being made, that aren't getting filtered due to `dont_filter`.

**Comment by aguilerapy** [comment]
We have `dont_filter=True` on `parse_pages` because a request with the expired token is queued again (with `process_request`, it doesn't download) and gets a new token, then it continues where the spider stopped, in which case it is the last queued request, and there we need `dont_filter=True`.

Right now we process requests one by one and middlewares checks if the token has expired.

**Comment by jpmckinney** [comment]
Hmm, well I'm not sure how the error occurs, but we should investigate further.

**Comment by jpmckinney** [comment]
The error has so far occurred 10k times, so I think there's a real bug to fix.

**Comment by jpmckinney** [comment]
Once we do #395, we'll know if the issue is on Kingfisher Collect's side.

**Comment by jpmckinney** [comment]
W

**Comment by jpmckinney** [comment]
While updating the logs documentation, I found 212 "WARNING: Duplicate File:" warnings in:

    /home/ocdskfs/scrapyd/logs/kingfisher/paraguay_dncp_releases/15151cf0f91511ea879e0c9d92c523cb.log

which was run on 2020-09-17. Can you check if the duplicates are real (in which case we can ignore the warnings) or if the spider needs to be fixed?

**Comment by yolile** [comment]
After the recent changes, the last log file

`/home/ocdskfs/scrapyd/logs/kingfisher/paraguay_dncp_releases/4c86d1167a1911ec90ee0c9d92c523cb.log`


Doesn't have any warnings about duplications.
