### ISSUE TITLE
PR review of #368

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#369]
https://github.com/open-contracting/kingfisher-scrape/pull/368/files

1. Let's use the `_write_file` method (we can promote it to a public method `write_file`) instead of running `makedirs` in the spider. Let's do the same for `georgia_opendata`.
    * Ideally, spiders should not be writing files, but that's to be solved in #277.
1. @aguilerapy had put `parse_json_lines` in `ZipSpider` for a reason. Rather than move the method, we should just have `DigiwhistBase` inherit from `ZipSpider`.

cc @odscjames @yolile

**Comment by yolile** [comment]
@jpmckinney 
> Rather than move the method, we should just have DigiwhistBase inherit from ZipSpider.

that would be kind of weird as DigiwhistBase don't use zip files

**Comment by jpmckinney** [comment]
Please coordinate with @aguilerapy on the preferred design. DigiwhistBase uses tar files, so we could rename the class `ArchiveSpider` since ZIP and TAR are archive formats.

**Comment by yolile** [comment]
@jpmckinney ok I will! But I personally think that those methods could be more general, as we can have non-archived files that are JSON lines etc

**Comment by jpmckinney** [comment]
Sounds good to me – I just want to make sure all developers are on the same page :)

**Comment by jpmckinney** [comment]
Ultimately makes sense to keep parse_json_lines in BaseSpider, so closing.
