### ISSUE TITLE
Fix sample download for Chile scrapers

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#388]
The sample download is very large in `chile_base`.

**Comment by jpmckinney** [comment]
Is this the same as #312?

**Comment by aguilerapy** [comment]
I don't think so, in `chile_base` is missing a question to stop the scraper if it's a sample.

**Comment by jpmckinney** [comment]
Let’s fix this in #84, which proposes a new way using existing Scrapy middleware, instead of having special code in each spider.

**Comment by yolile** [comment]
this was already fixed in #385
