### ISSUE TITLE
Fix Dominican Republic scraper

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#390]
It raises `rarfile.BadRarFile: Failed the read enough data`.

**Comment by jpmckinney** [comment]
The files from https://www.dgcp.gob.do/estandar-mundial-ocds/ work fine manually, so I guess it is a code issue.

**Comment by aguilerapy** [comment]
Now raises `IDNAError('Empty domain')` when trying to access: "https:///http://www.dgcp.gob.do/new_dgcp/documentos/andres/JSON_DGCP_2019.rar>"

**Comment by jpmckinney** [comment]
Hmm, well there should be multiple protocols: `https:///http://`
