### ISSUE TITLE
Consider Autothrottle extension for spiders with HTTP 429 errors

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#397]
https://docs.scrapy.org/en/latest/topics/autothrottle.html

Affects:

* ~~afghanistan_records~~ (`download_delay`) #824
* ~~afghanistan_releases~~ (`download_delay`) #824
* ~~colombia~~ (custom logic for delays) (logic was removed?)
* [x] paraguay_dncp_records (custom logic for attempts to get access token)
* [x] paraguay_dncp_releases (custom logic for attempts to get access token)
* [x] paraguay_hacienda (custom logic for attempts to get access token)
* ~~tanzania_zabuni~~ (`download_delay`) #879

Ideally, we'd configure it to match documented rate limits by the publisher.

**Comment by jpmckinney** [comment]
Afghanistan already uses `download_delay`, but I'm not sure if it's based on documentation or experience.

**Comment by jpmckinney** [comment]
I think we might also try to configure `colombia` using the autothrottle extension, instead of having retry logic.

**Comment by yolile** [comment]
I'm not sure if this will actually help us with the 40x errors problem. The [documentation](https://docs.scrapy.org/en/latest/topics/autothrottle.html#throttling-algorithm) says that 

> when a response is received, the target download delay is calculated as latency / N where latency is a latency of the response, and N is AUTOTHROTTLE_TARGET_CONCURRENCY.

and 

> latencies of non-200 responses are not allowed to decrease the delay;

So I think that this is useful when a server starts to taking longer to respond but not when the server starts to respond with errors

**Comment by jpmckinney** [comment]
Indeed - it doesn't implement backing off. There are a couple open issues:

* https://github.com/scrapy/scrapy/issues/4424 (has a PR)
* https://github.com/scrapy/scrapy/issues/802

**Comment by jpmckinney** [comment]
@yolile Looks like the recent uk_contracts_finder collection caused a lot of 429 errors: https://sentry.io/organizations/open-contracting-partnership/issues/2086237643/events/?project=5287294&statsPeriod=14d

**Comment by yolile** [comment]
I will mark this one as blocked, as we depend on scrapy. The last update https://github.com/scrapy/scrapy/pull/5015#issuecomment-858715460 is that they are planning to include this in the next version of scrapy but they don't know when that version will be released. But we could use our `DelayedRequestMiddleware` instead.

**Comment by jpmckinney** [comment]
> I'm not sure if this will actually help us with the 40x errors problem. The [documentation](https://docs.scrapy.org/en/latest/topics/autothrottle.html#throttling-algorithm) says that
> 
> > when a response is received, the target download delay is calculated as latency / N where latency is a latency of the response, and N is AUTOTHROTTLE_TARGET_CONCURRENCY.
> 
> and
> 
> > latencies of non-200 responses are not allowed to decrease the delay;
> 
> So I think that this is useful when a server starts to taking longer to respond but not when the server starts to respond with errors

I don't think there is a problem with Autothrottle:

> * often non-200 (error) responses can be returned faster than regular responses, so with a small download delay and a hard concurrency limit crawler will be sending requests to server faster when server starts to return errors. But this is an opposite of what crawler should do - in case of errors it makes more sense to slow down: these errors may be caused by the high request rate.
>
> AutoThrottle doesn’t have these issues.

In other words, if concurrency is 1, then the download delay matches the response time (latency) of successful requests. Error responses don't affect the download delay.

There are 5 spider files that use `download_delay`, excluding unavailable spiders (afghanistan x3, tanzania, uganda) and blocked spiders (croatia). The most recent authors are:

- honduras_portal_api_base (Yohanna)
- mexico_quien_es_quien_base (Cecilia)
- nigeria_portal (Rodrigo)
- openopps (James)
- uruguay_base (Yohanna)

Could we either:

1. Try autothrottle on these, to see if it achieves low error rates
2. Add a comment explaining why the specific delay is needed

In general, whenever we limit performance with `download_delay` or `CONCURRENT_REQUESTS`, we should document why, so that we can review whether it is still true at a later date.

(Also, I don't know why a download_delay of 0.9 is used... It's not much different from 1.)

**Comment by yolile** [comment]
* honduras_portal_api_base (Andrés) https://github.com/open-contracting/kingfisher-collect/pull/496
* uruguay_base (Romi) https://github.com/open-contracting/kingfisher-collect/pull/35

But anyway, I don't remember why we start using 0.9 instead of 1 either

**Comment by jpmckinney** [comment]
Yes, I named the people who had edited lines and who still work at OCP or CDS :)

**Comment by yolile** [comment]
Current spiders using `download_delay` are:
- `croatia`
- `honduras_portal_api_base`
- `mexico_quien_es_quien_releases`
- `uruguay_base`

I tested and all of them are working fine without the download_delay setting, but `honduras_portal`.  Honduras starts returning `502 Bad Gateway` errors for deep pages, e.g. https://www.contratacionesabiertas.gob.hn/api/v1/release/?format=json&page=10000, I don't think this error is related to the download_delay parameter, so I think it is fine to remove the parameter from all the spiders above.

`indonesia_opentender` also uses download_delay but their case is documented and `openopps` has its own middleware

**Comment by jpmckinney** [comment]
Sounds good! We can then close this issue. If Scrapy improves its features, we can consider it in a new issue.
