### ISSUE TITLE
australia_nsw: Check pagination logic

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#399]
For the tender and contract search endpoints, it seems to return a next link, even if the current page contains no data (you can set an arbitrarily large `startRow` and it will return a response with a new `next` link).

**Comment by nativaldezt** [comment]
I imagine the problem here is that the spider never ends. 
It could be the solution to add the condition 
`len(data ['releases'])> 0 and` 
to
`if 'links' in data and isinstance(data['links'], dict) and 'next' in data['links']:`
?

**Comment by yolile** [comment]
add `and  data['releases']` should do the trick
