### ISSUE TITLE
scotland: Check API request format

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#401]
I tried to follow the date format at https://api.publiccontractsscotland.gov.uk/v1/ However, I get the same result no matter what `mm-yyyy` I submit. The spider uses `yyyy-mm-dd` format, which also doesn't seem to have any effect.

@mrshll1001: Do you happen to know what the correct API format is?

Once we sort this out, we can use the new `date_range_by_month` helper, and also set the start date correctly (instead of 364 days before today).

**Comment by mrshll1001** [comment]
Are we reading just the `publishedDate` field in the API? I think that stays the same as the OCDS is generated on the fly and is thus published "today" semantically.

If I make a request for [10-2019](https://api.publiccontractsscotland.gov.uk/v1/Notices?dateFrom=10-2019&noticeType=2&outputType=1) my `releasePackage/publishedDate` field reads for today (2020-06-01) but the dates of the releases are all for October 2019. I get similarly appropriate results for running a query for [12-2019](https://api.publiccontractsscotland.gov.uk/v1/Notices?dateFrom=12-2019&noticeType=2&outputType=1) and [02-2020](https://api.publiccontractsscotland.gov.uk/v1/Notices?dateFrom=02-2020&noticeType=2&outputType=1)

Did I misunderstand the problem?

**Comment by jpmckinney** [comment]
Aha – the reason the results weren't changing for me is because I was testing with `dateFrom` values that were earlier than the earliest possible date, so the first result always stayed the same.

The spider code says the API only goes a year back (364 days to be precise). Why is that? Will that always be the case? It's not documented publicly, as far as I can see.

Also, the spider seems to advance the date by 14 days at a time, but as far as I can tell, there is no way to paginate, and the only way to advance is 1 month at a time via the `dateFrom` parameter.

**Comment by yolile** [comment]
I think this was solved as part of #438
