### ISSUE TITLE
Send job id to Kingfisher Process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#411]
* spider args: so that analysts can see which filters were applied
  * `spider_arguments` is calculated in `BaseSpider.__init__` and can be extracted to a method
* [x] OCDS version: so Kingfisher Process knows whether to upgrade
  * `ocds_version` class attribute on all spiders
* job id: to more easily reconcile Scrapyd jobs with collections
  * The `_job` spider argument, set by Scrapyd
* code version: to know which version of a spider was run (for troubleshooting)
  * I think Scrapyd sets a `SCRAPY_EGG_VERSION` environment variable only if a specific version was scheduled. We might be able to determine the latest egg, but we won't have something like a git commit SHA.

Blocked waiting for V2 of Kingfisher Process.

**Comment by jpmckinney** [comment]
We might also want to put the git commit in the crawl stats, if possible, to more clearly indicate what code was run.

**Comment by jpmckinney** [comment]
Moving from #346 (same as "send … spiders args" from issue title):

> Update Kingfisher Process, so that it stores the filters on its end, as well. https://github.com/open-contracting/kingfisher-process/issues/270

**Comment by jpmckinney** [comment]
Moving crawl stats to #582 since it is sent at the end, not at the start, of a collection.

**Comment by jpmckinney** [comment]
> spider args: so that analysts can see which filters were applied

@yolile Do you know if this is a real analyst need, or just something I invented? The person scheduling the crawl will remember what they did/why they did it. I think the only use case is if another analyst later goes looking for an existing collection. I don't know how often this happens, however.

> code version: to know which version of a spider was run (for troubleshooting)

I might have been imagining scenarios that don't occur. I think we generally deploy spiders fairly soon after updating them, and if there is an error I'm not sure how useful this feature will be, since it won't be a git commit, but something else.

If they're not needed, all that's left is the job id, which is useful and relevant to integrating #531 into helpdesk operations.

**Comment by yolile** [comment]
> @yolile Do you know if this is a real analyst need, or just something I invented?

I think that we normally use the 'note' feature to indicate anything special about the collection.  

>  I don't know how often this happens, however.

It happens sometimes for collections like Colombia, which for example Camila uses quite often, but that is the exception rather than the rule, I guess. That said, I think it could be a nice thing to have, but we can live without it or use #531

**Comment by jpmckinney** [comment]
The notes are mostly "Started by NAME". EIther analysts rarely apply filters, or they rarely make a note about it.

For use cases like Camila's, I think the ideal solution is a frontend with a list of collections, with data from the logreport. We can do that using #531, without add more to the create_collection API. WIthout a frontend, we can still share commands on how to run the logreport from the command-line. This seems to be an infrequent task, so we can start with that.

Unless you have an opinion on somehow tracking the code version, I think there's just the job ID to do.

**Comment by jpmckinney** [comment]
Corresponding issue in Kingfisher Process is https://github.com/open-contracting/kingfisher-process/issues/341

**Comment by yolile** [comment]
> For use cases like Camila's, I think the ideal solution is a frontend with a list of collections, with data from the logreport.

I guess we can also do that with a query in redash that for each collection, get the max and min release dates (the date range is the most common filter used) ([example](https://redash.open-contracting.org/queries/334?p_source_id=colombia) without dates), and that can act as the front end, but probably that query will be slow for big datasets as Colombia

**Comment by jpmckinney** [comment]
Yeah, that query will be very slow. Once I've deployed the new software everywhere, and we've done open-contracting/kingfisher-process#341, we can start thinking about how to address open-contracting/kingfisher-process#295.
