### ISSUE TITLE
Change LinksSpider to error if the next link isn't found on the first page

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#412]
It's okay for the next link to not be found on subsequent pages, but it should be required on the first page.

**Comment by jpmckinney** [comment]
Let's create a new exception class instead of inheriting from `KingfisherScrapyError`. Also, the test should check whether the exception is *only* raised on the first page, and not on subsequent pages.

**Comment by yolile** [comment]
@jpmckinney @aguilerapy  With the from_date and until_date parameters, there are cases where it is ok to don't have a next link in the first page (eg when scraping just one day)

**Comment by jpmckinney** [comment]
@yolile We can add that condition to the LinksSpider.
