### ISSUE TITLE
Update bulk download scrapers to scrape from pages instead of using hard coded URLs

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#414]
This includes at least : 

- [x] Chile https://desarrolladores.mercadopublico.cl/OCDS/DescargaMasiva
- [x] Canada Buyandsell https://buyandsell.gc.ca/procurement-data/open-contracting-data-standard-pilot/download-ocds-pilot-data
- [x] Honduras http://www.contratacionesabiertas.gob.hn/descargas/
- [x] Uruguay https://www.gub.uy/agencia-compras-contrataciones-estado/datos-y-estadisticas/datos/open-contracting
- [x] Nepal http://ppip.gov.np/downloads

**Comment by nativaldezt** [comment]
So, the idea is to get the download URLs from the page instead of assuming it is a certain way?
This is to prevent the spider from stopping working if the link changes? that is more likely to happen than the page being changed?

**Comment by yolile** [comment]
> So, the idea is to get the download URLs from the page instead of assuming it is a certain way?

Yes

> This is to prevent the spider from stopping working if the link changes?

Yes, but also to get a better chance to know if they have added more links and download the new links too, not just the fixed ones that we may be aware of

**Comment by yolile** [comment]
update, for Honduras I see that they actually have an endpoint that lists all the available URLs, so we can use that  one http://www.contratacionesabiertas.gob.hn/api/v1/descargas/

**Comment by Ravf95** [comment]
Hi @yolile.  I started with the chile_compras_bulk spider and I see that the load dates in https://desarrolladores.mercadopublico.cl/OCDS/DescargaMasiva  work with a request to https://api.mercadopublico.cl/APISOCDS/Utilidades/DescargaMasiva and this calls to the javascript function [ListItems(initYear)](https://api.mercadopublico.cl/APISOCDS/Utilidades/Scripts/descarga-masiva.js) to load data in `div #contentList`, so the load data requires an initial year for iterate to current year. I think that the spider doesn't require changes, what do you think?

**Comment by yolile** [comment]
Yes, makes sense, and they are also documeting the use as "En caso de querer descargar los archivos mediante programas, es posible hacerlo mediante URLs en las que se modifique la fecha del archivo de la forma: https://ocds.blob.core.windows.net/ocds/yyyymm.zip", so we are already using the service as expected, as they consintently publish a file per year-month.

**Comment by yolile** [comment]
I think that we can also skip Canada Buyandsell, as they have more links than the ones listed on their page.

**Comment by Ravf95** [comment]
Yes, for the Nepal site the date list it's contained in `div #app` and this content it's generated by  obfuscated javascript file functions defined in http://ppip.gov.np/dist/app.js. I think we can ask the publisher if exists another method to request them.

**Comment by yolile** [comment]
:disappointed: ok, they are no longer publishing updated data anyway

**Comment by Ravf95** [comment]
For Honduras we can use `SimpleSpider class` and parse [the available downloads](https://www.contratacionesabiertas.gob.hn/api/v1/descargas/) by the "sistema" and "publicador" fields for later download it.

**Comment by Ravf95** [comment]
@yolile I think we can close

**Comment by jpmckinney** [comment]
In short:

* Chile: already works as intended
* Canada Buyandsell: HTML contains fewer URLs than our hardcoded URLs
* Honduras: #804
* Uruguay: ???
* Nepal: Hard to do, and not updating, anyway

Looking at Nepal's code, the link generation section does:

```js
var e = function (e) {
  var t = (new Date).getFullYear(), a = [];
  for (e = e || 2013; e <= t;) a.push(e++);
  return a;
};
```

Which just means "each year from 2013 onward".

**Comment by yolile** [comment]
Uruguay was updated in https://github.com/open-contracting/kingfisher-collect/pull/705

**Comment by jpmckinney** [comment]
Assuming there aren't any others with hardcoded URLs, I think we can close.
