### ISSUE TITLE
Update colombia scraper to no retry after a 404 error

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#415]
The Colombia API changed and now if a link returns 404 it means that there are no more pages
We can update the API to include from_date parameter too

**Comment by jpmckinney** [comment]
Let's reuse (or improve) the logic in BaseSpider for setting the default from/until date, instead of having that logic in the individual spider. The Colombia spider should just be concerned with setting the `date_format` class variable and with calling `strftime`.
