### ISSUE TITLE
Add spider for Ecuador COVID-19 emergency publication

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-collect#418]
**Links to bulk download and/or API endpoints**
https://portal.compraspublicas.gob.ec/sercop/data-estandar-ocds/

**Link to CRM issue**
https://crm.open-contracting.org/issues/4397

**Priority**
Low

**Comment by yolile** [comment]
Each link in https://portal.compraspublicas.gob.ec/sercop/data-estandar-ocds/ redirects to a download site with a generated "Download" button, so it seems like we cannot automatize the download. I tried using the final download link (the one that the browser uses when the Download button is pressed) but the site redirects to the original one again in scrapy.

**Comment by jpmckinney** [comment]
Strange. I tried "Copy as cURL" in Chrome:

```
curl 'https://cloud.sercop.gob.ec:5001/fsdownload/bsYZfzwrf/ocds-2020-06-29.json' \
  -H 'authority: cloud.sercop.gob.ec:5001' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'dnt: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'referer: https://cloud.sercop.gob.ec:5001/sharing/bsYZfzwrf' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: sharing_sid=Aa7P3sI6q5kFJ0D3pizDFnDkEBsvcUft' \
  --compressed
```

But get this error:

```
{"error":{"code":117},"success":false}
```

The difference across requests is the cookie (e.g. another `sharing_sid` is `rXQDA_YuXVZnERpnYyqa-3mj9aR_oVb9`). This cookie is set when requesting the page.

If I reload the page and copy the cookie value into the cURL above, I get the JSON response. So, we need to look into cookies in Scrapy.

**Comment by jpmckinney** [comment]
We can set `COOKIES_DEBUG = True` to check that the cookie is being used (which it should by default): https://docs.scrapy.org/en/latest/topics/downloader-middleware.html?highlight=referer#cookies-debug

Also, referers should automatically be populated: https://docs.scrapy.org/en/latest/topics/spider-middleware.html#module-scrapy.spidermiddlewares.referer

The problem might be that simultaneous requests causes the wrong cookie to be used for a given download. So, we maybe need to make max concurrent requests be 1.

**Comment by jpmckinney** [comment]
Notes from call: We need to carefully order to requests (get cookie, use cookie, then repeat for next page).

However, since Scrapy/Twisted is asynchronous, it might send multiple "get cookie" requests (one at a time) before it receives the first response. I'm not aware of a way to make Scrapy process a response before sending a request.

So, we might need to use Twisted's [treq](https://github.com/twisted/treq) library in order to control the sequence.
