### ISSUE TITLE
Add spider for new Moldova endpoint

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#419]
**Links to bulk download and/or API endpoints**
https://public.mtender.gov.md/tenders
http://public.eprocurement.systems/ocds/tenders/

**Link to CRM issue**
https://crm.open-contracting.org/issues/6128

**Priority**
medium

**Comment by jpmckinney** [comment]
Please move the `base_url` class variable into the `parse_list` method. We avoid class variables unless they need to be reused across multiple methods.

Also, I'm not sure that it makes sense to configure the `formatter` to return the "tenders" path component. I think it's better to follow the same pattern as https://github.com/open-contracting/kingfisher-collect/blob/master/kingfisher_scrapy/spiders/canada_montreal.py where the first page is set to 'offset-0.json' and subsequent pages are named after the query parameter only.
