### ISSUE TITLE
indonesia_bandung: Update documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#423]
There is much private documentation shared in this CRM issue: https://crm.open-contracting.org/issues/5670#note-18

We should add it to our docstring, since it's not yet available from the publisher's website.

**Comment by aguilerapy** [comment]
Looks like https://birms.bandung.go.id/api/contracts/year/{year}?page={page} (defined in the CRM issue) and https://birms.bandung.go.id/api/packages/year/{year}?page={page} (endpoint used in the scraper) it's the same.
