### ISSUE TITLE
Honduras ONCAE: Update sample to download a package for each system

### ISSUE THREAD

**Issue by romifz** [open-contracting/kingfisher-collect#429]
ONCAE data comes from three different modules/systems:

* HonduCompras 1.0 - Módulo de Difusión de Compras y Contrataciones
* Módulo de Difusión Directa de Contratos
* Catálogo Electrónico

The sample parameter should download a package for each one, since the fields available may change depending of the source.

**Comment by jpmckinney** [comment]
Related: #125
