### ISSUE TITLE
colombia: Fix scraper file name

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#430]
The filename is taken from the "page" parameter but this page remains the same through all the pages after the 2nd one. We should use the "id" parameter instead.

**Comment by jpmckinney** [comment]
Oops! I think my mistake.

Also, I think it's not possible to combine both the `year` and from/until date spider arguments, right? In that case, we should error when initializing the spider if both are provided.

**Comment by yolile** [comment]
Yes, you are right, I included that validation too
