### ISSUE TITLE
scotland_proactis: Code review

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#458]
* [x] The `parse_requests` method doesn't parse requests; it yields requests. So it would be clearer to name it `yield_requests`. Alternately, we can have a class variable like in kenya_makueni to store the URL pattern, and then we can just put the logic from `parse_requests` in the typical `start_requests` method.
* [x] We don't need this line: `start = date(self.from_date.year, self.from_date.month, 1)`. When parsing a year-month date, the day is already set to `1`.
* [x] To set the default from date, we should use the same pattern as in paraguay_dncp_base and uruguay_base. That way, we don't need this line: `start = date(now.year - 1, now.month, 1)`.
* [x] To format dates, we'd typically use `d.strftime('%m-%Y')` not `'{:02d}-{:04d}'.format(d.month, d.year)`.

**Comment by aguilerapy** [comment]
>     * [ ]  We don't need this line: `start = date(self.from_date.year, self.from_date.month, 1)`. When parsing a year-month date, the day is already set to `1`.
> 
Replacement by `start = self.from_date`
>     * [ ]  To set the default from date, we should use the same pattern as in paraguay_dncp_base and uruguay_base. That way, we don't need this line: `start = date(now.year - 1, now.month, 1)`.
> 
I made the default from_date dynamic because the API docs say data is kept up to a year old. They changed the documentation and I no longer see this restriction.
