### ISSUE TITLE
Allow users to specify any query string parameters

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#470]
#346 is about adding a few common spider arguments, so that a user can set `-a from_date=2001-01-01` and not have to learn each API's parameter for that concept.

However, some users might know an API's parameters and want to use them.

With this feature, the user can add multiple spider arguments like `-a qs=offset:123456789 -a qs=buyer:xyz` and then `offset=123456789&buyer=xyz` would be added to the URLs in `start_requests`.

**Comment by yolile** [comment]
closed by #504
