### ISSUE TITLE
CompressedFileSpider: process compressed files is useless when KingfisherProcess is not configured

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#471]
Currently, this class saves the original file to disk and yields the compressed files to the KingfisherProcess extension, so if the user is not using Kingfisher Process this process is useless. 

So maybe we can ask if `KINGFISHER_API_URI` is set and if it is not, skip this process.

**Comment by jpmckinney** [comment]
Hmm, when we add support for CompressedFileSpider spiders to the Pluck pipeline, we'll want to yield at least some of the file items for the pipeline to process.

We can maybe add a spider argument to override `compressed_file_format`. If `compressed_file_format` isn't 'json_lines' or 'release_package', then the original file is saved to disk without further processing.

**Comment by jpmckinney** [comment]
Let's first try adding support for compressed files to the Pluck pipeline. It might be that we need to use a different strategy when decompressing for plucking than when decompressing for Kingfisher Process. If that's the case, we can move the `compressed_file_format` logic into a new pipeline that has lower priority than the Pluck pipeline, and that is only activated if Kingfisher Process is configured.

**Comment by jpmckinney** [comment]
Related: #449 

Potentially related: #410

**Comment by jpmckinney** [comment]
In follow-up to #329, check if we can get rid of `CompressedFileSpider.parse = yield_nothing` in crawlall.

**Comment by jpmckinney** [comment]
Noting that #572 adds middlewares such that archives are decompressed, and their contents are written to disk.
