### ISSUE TITLE
Bolivia Agetic spider

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#490]
**Links to bulk download and/or API documentation**
https://datos.gob.bo/id/dataset/contrataciones-agetic-2019-estandar-ocp

**Link to CRM issue**
https://crm.open-contracting.org/issues/6094

**Priority**
anytime

Note that they are publishing CSV files

**Comment by jpmckinney** [comment]
We can use the `unflatten` command in Flatten Tool to get the JSON to send onwards.
