### ISSUE TITLE
Add scraper for Nicaragua: Solid Waste Mitigation Platform

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#493]
**Links to bulk download and/or API documentation**
http://swmp.gekoware.com/ocds-api.xhtml

**Links to bulk download and/or API endpoints**
http://www.gekoware.com/swmp/api/ocds/{From date: yyyymmdd}/{To date: yyyymmdd}

**Link to CRM issue**
https://crm.open-contracting.org/issues/6436

**Priority**
anytime

**Comment by aguilerapy** [comment]
Documentation is no longer online. All releases are accessible from http://www.gekoware.com/swmp/api/ocds/20000101/20201231.
