### ISSUE TITLE
Research whether publishers support incremental updates

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#501]
For APIs, we will need to research:

1. How frequently is it updated? (multiple times a day, once a day, or otherwise)
1. Does it offer sorted results?
    * For example, if releases are sorted in reverse order based on publication time, we can download releases until we meet an `ocid` and `id` pair that we've already seen, and then stop.
1. Is sorting consistent?
    * For example, if the resolution of the release `date` is low (e.g. date not time), there might be multiple releases with the same `date`. If so, we would want those releases to always appear in the same order, not in an arbitrary order.
1. Is pagination consistent?
    * For example, if data is updated multiple times a day, then new results might be added to the first page, shifting existing results to the next page.
1. Does it offer time-based filters?
    * For example, if an API can be filtered to return results after a given time, then, after each collection, we can keep track of the most recent release `date`, and then start from there on the next collection.
1. What is the resolution of the time-based filter?
    * If the API offers time-based filters, but they are not fine-grained (e.g. date not time), then, as long as the sort order is consistent, we can start from the stored date, but ignore data we've already seen (like with sorted results).
1. Are releases immutable?
    * OCDS discourages changes to existing releases. However, some publishers, when updating their mapping, might change the release without updating its `date`. This means we could miss the changes using the above methods. We could maybe compare old and new collections of the same source.
1. Are there multiple releases per OCID?
    * If not, then it is much simpler to incrementally compile releases.

References: https://extensions.open-contracting.org/en/extensions/pagination/master/

## Records

It's not clear how to do incremental updates on record APIs. For example, if a release is added to a record, we would need to know that we already collected its other releases.

It's also not clear how sorting works on record APIs. If a release is added to a record, does that record jump to the first page of results when sorting by reverse chronology? If so, then, if this occurs during a collection, we might miss that record entirely (for example, it was originally on page 10, then moved to page 1, while the spider was on page 5).

It's also not clear how filters work on record APIs. For example, does the date filter need to match *any* release in the record, the *first* release, the *last* release, or *all* releases?

**Comment by jpmckinney** [comment]
Could this be prioritized for Afghanistan, Chile, Moldova and Portugal? It's relevant to an upcoming project.

cc @nativaldezt @yolile

**Comment by yolile** [comment]
@jpmckinney sure! where should we answer the questions? in the spiders' documentation themself or in a separate document?

**Comment by jpmckinney** [comment]
We can maybe start a spreadsheet for now (questions as rows, sources as columns), and decide later what to do with the content.

**Comment by jpmckinney** [comment]
We can use this Drive folder: https://drive.google.com/drive/folders/1S1ZmTAccUxvL87uGFFBvi5ZtFe5K_OWT

**Comment by yolile** [comment]
@jpmckinney should we close this issue now?

**Comment by jpmckinney** [comment]
I guess so. We have the sheet now if we need to research additional publishers.
