### ISSUE TITLE
Possible issue with httpstat.us

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/kingfisher-collect#505]
[In the cove-ocds tests we've had problems with httpstat.us returning the wrong codes](https://github.com/open-contracting/cove-ocds/issues/82), I did a [A GitHub search](https://github.com/search?q=org%3Aopen-contracting+httpstat.us&type=code)  and this repo is the other place we use http://httpstat.us (and only in the tests).

Don't know if this is worth trying to fix pre-emptively, or maybe this issue might help someone find the issue quicker if it does start failing.

**Comment by jpmckinney** [comment]
It's not used in a test but in a spider that is confusingly named `test_fail`, so its use is okay.
