### ISSUE TITLE
Adjust outputType parameter in scotland_public_contracts

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-collect#509]
The [Scotland Public Contracts API](https://api.publiccontractsscotland.gov.uk/v1) says that `outputType=0` should be requested for OCDS output.

In a recent scrape, all requests were made using `outputType=1`. I believe that this is probably inherited from the scotland_base spider.

**Comment by aguilerapy** [comment]
The correction was made in  #469 but not deployed, now it is.

**Comment by jpmckinney** [comment]
@mrshll1001 Can we delete the https://sandbox4.proactislabs.com/v1/Notices spider? Has their recent work been deployed to https://api.publiccontractsscotland.gov.uk/v1/Notices?

**Comment by yolile** [comment]
@mrshll1001 @jpmckinney in fact https://sandbox4.proactislabs.com/v1/Notices is not working anymore (404) so can we delete the spider?

**Comment by jpmckinney** [comment]
Yes, please go ahead :)
