### ISSUE TITLE
Add start_page and end_page spider arguments

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#529]
We can start with the `IndexSpider` and `LinksSpider` subclasses that use integer pagination (i.e. `page` or `pageNumber` is 1, 2, 3, etc.).

**Comment by jpmckinney** [comment]
Noting from call with @yolile that this is only really useful if we can also set the sort order so that the results are consistent, e.g. if we can set releases to be listed in chronological order, then page=3 should return the same results each time. If we can't set the sort order, then the spider arguments don't have a good use case except for debugging.

**Comment by yolile** [comment]
As we haven't seen the need for this filter, and as we found filter by date more useful, I will close the issue
