### ISSUE TITLE
Scrapyd scrapy 2.X deprecation warnings

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#535]
After upgrading scrapy to 2.x we are getting some warnings from scrapyd
```
kingfisher-collect/.ve/bin/scrapyd-deploy:23: ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated, Please import from `w3lib.http` instead.
  from scrapy.utils.http import basic_auth_header
Packing version 1603828803
kingfisher-collect/.ve/bin/scrapyd-deploy:259: ScrapyDeprecationWarning: Call to deprecated function retry_on_eintr.
  retry_on_eintr(check_call, [sys.executable, 'setup.py', 'clean', '-a', 'bdist_egg', '-d', d], stdout=o, stderr=e)
```
related https://github.com/scrapy/scrapyd/issues/362
https://docs.scrapy.org/en/latest/news.html#id2
https://docs.scrapy.org/en/latest/news.html#id40

**Comment by jpmckinney** [comment]
There are multiple PRs for these at https://github.com/scrapy/scrapyd-client/pulls

**Comment by jpmckinney** [comment]
Hmm, these deprecations become errors in Scrapy 2.5: https://github.com/scrapy/scrapyd-client/issues/72

**Comment by jpmckinney** [comment]
I forked it and fixed the warnings: https://github.com/open-contracting/scrapyd-client

If development resumes or if a better fork appears, we can switch back.

I just don't want to be stuck on old versions of Scrapy, and scrapyd works well enough (and I don't remember finding good alternatives last time I checked).
