### ISSUE TITLE
portugal_records and portugal_releases return only a subset of the data

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#545]
According to the publisher, the API contains the same data as the bulk file (>1.5 million records) but `portugal_records` returns c. 500 records and `portugal_releases` returns only c. 4,000 releases.

I checked `collection_file` and there are a handful of errors reported, but otherwise the spider seems to have run successfully:

id | collection_id | filename | warnings | url | errors
-- | -- | -- | -- | -- | --
157,599,196 | 1,539 | offset-55.json | [NULL] | http://www.base.gov.pt/api/Record/GetRecords?offset=55 | {"http_code": 503}
157,598,197 | 1,539 | ocid-ocds-px0z7d-4457164-6424548-1.json | [NULL] | http://www.base.gov.pt/api/Record/GetRecordByOCID?ocid=ocds-px0z7d-4457164-6424548-1 | {"http_code": 503}
157,598,183 | 1,539 | ocid-ocds-px0z7d-4352773-6422690-1.json | [NULL] | http://www.base.gov.pt/api/Record/GetRecordByOCID?ocid=ocds-px0z7d-4352773-6422690-1 | {"http_code": 503}
157,598,175 | 1,539 | ocid-ocds-px0z7d-4376315-6417617-1.json | [NULL] | http://www.base.gov.pt/api/Record/GetRecordByOCID?ocid=ocds-px0z7d-4376315-6417617-1 | {"http_code": 503}
157,598,149 | 1,539 | ocid-ocds-px0z7d-4460028-6430538-1.json | [NULL] | http://www.base.gov.pt/api/Record/GetRecordByOCID?ocid=ocds-px0z7d-4460028-6430538-1 | {"http_code": 503}
157,597,864 | 1,542 | offset-404.json | [NULL] | http://www.base.gov.pt/api/Release/GetReleases?offset=404 | {"http_code": 429}

I'm following up separately with the publisher about the packaging and pagination issues.

**Comment by duncandewhurst** [comment]
cc @mrshll1001

**Comment by yolile** [comment]
This was a bug indeed, my bad at https://github.com/open-contracting/kingfisher-collect/pull/522/commits/f6fd2b5b77d9028ac810fe777e86fb21e9f73523  @duncandewhurst  the change is deployed now, and I ran the two collections again so you can check again on Monday

**Comment by duncandewhurst** [comment]
Thanks @yolile!

The spiders still return many fewer releases and records than in the bulk file, but I don't see that many errors in `collection_file`.

Could you double-check the spiders and let me know if there is an issue I should report to the publisher?

**Comment by duncandewhurst** [comment]
The publisher has now updated the GetReleases and GetRecords endpoints so they now return a single package with the pagination extension. There is an issue with the `previous` links but it should be possible to page forward through the results to get all the data.

Please could you update the scraper? Lindsey asked us to prioritise feedback to Portugal (after Budeshi and OnData).

**Comment by yolile** [comment]
@duncandewhurst the GetReleases service is down now, but I started the record scraper in the server

**Comment by duncandewhurst** [comment]
Thanks @yolile! The scraper stopped after a 503 error on http://www.base.gov.pt/api/Record/GetRecords?offset=36801.

It just tried `curl`ing that URL and it seems to return intermittent 503 errors. GetReleases seems to have the same issue, so I'll report those to the publisher.

Can the number of retries be adjusted on the scraper to give it a better chance of finishing?

**Comment by jpmckinney** [comment]
We can use `custom_settings` to change `RETRY_TIMES` in the spider, but in the meantime you can run the spider with `-d setting=RETRY_TIMES=4`. We can add this to the docs.

https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#std-setting-RETRY_TIMES

**Comment by duncandewhurst** [comment]
I reran the scrapers with `setting=RETRY_TIMES=4` and the records scraper failed with error 429 and the releases scraper failed with error 503.

I've asked the publisher if there is a rate limit we need to respect.

**Comment by jpmckinney** [comment]
We previously had `download_delay = 1` but #553 removed it.

**Comment by yolile** [comment]
@duncandewhurst  I have added the download_delay again and also set `RETRY_TIMES` to 10, I deployed the changes and started both spiders again (releases and records)

**Comment by yolile** [comment]
well, both failed again beside the 10 retries, at http://www.base.gov.pt/api/Release/GetReleases?offset=35201 and http://www.base.gov.pt/api/Record/GetRecords?offset=36101

**Comment by duncandewhurst** [comment]
Thanks, @yolile.

The publisher has now increased the timeout value on the server so I tried running the scrapers again (45d58b88246511ebaad50c9d92c523cb and 3dd68892246511ebaad50c9d92c523cb) and this time they failed immediately after 10 attempts which returned 500 errors.

I checked using `curl` and both endpoints seemed to be working OK, so I've started the scrapers again and they seem to be running OK this time.

**Comment by jpmckinney** [comment]
Has there been any change in their API's performance? This is relevant to an upcoming project.

**Comment by duncandewhurst** [comment]
[Last time we ran it the scraper failed due to 503 errors](https://crm.open-contracting.org/issues/6093#note-54) and the publisher hasn't got back to us since we reported them.

I just tried to run it again and it [failed due to 500 errors](https://collect.kingfisher.open-contracting.org/logs/kingfisher/portugal_releases/692f8f3256b711eb85470c9d92c523cb.log).

I'll ask Matt to follow up with them.

**Comment by yolile** [comment]
> Edit: However, accessing http://www.base.gov.pt/api/Release/GetReleases in a browser works, so we should check the scraper before following up with the publisher.

Well, not always :( 

![image](https://user-images.githubusercontent.com/6834122/104723155-96bb9800-570d-11eb-8ae2-62bf244804dd.png)

**Comment by yolile** [comment]
but I will try using scrapy [auto throttle](https://docs.scrapy.org/en/latest/topics/autothrottle.html) as discussed with @jpmckinney

**Comment by jpmckinney** [comment]
@yolile Have you noticed whether later results take longer to prepare (and whether they fail more frequently)?

It could be that Portugal is using limit/offset for pagination, which runs into severe issues at high offsets, compared to cursor pagination (example article: https://medium.com/swlh/why-you-shouldnt-use-offset-and-limit-for-your-pagination-4440e421ba87)

**Comment by yolile** [comment]
@jpmckinney my last run failed again after 5 consecutive attempts to the same page (I will try again with another strategy) but, the pages where the API returned 50x errors were:

```
36201
72401
108601
145201
181501
217701
254101
290201
326301
362601
399001
435401
471501
507501
543701
580001
616501
652501
688701
724701
760901
```

This means that the API fails around every 36100~36600 pages (and as you can see it didn't fail more in later results, it is something even weirdest!)

**Comment by jpmckinney** [comment]
That’s surprisingly regular! Are the requests once per second? If so that would mean something happens on their end every 10 minutes.

**Comment by yolile** [comment]
These are the durations between fails:


```
0:12:02
0:12:56
0:12:50
0:12:20
0:13:50
0:13:12
0:14:52
0:17:33
0:18:49
0:20:28
0:18:56
0:18:21
0:19:39
0:20:50
0:22:28
0:25:35
0:24:23
0:24:05
0:28:44
0:32:15
```

As you can see the more it fails, the more time it takes to fail again. But I noticed that after each "recovery" (that is wait 180 seconds and try again) the API responds again but it takes longer to respond for a number of requests, and then, after X number of requests, it works "normally" again (around 1 and 6 seconds per request).

**Comment by jpmckinney** [comment]
On our call, given failures occur after a consistent number of requests (about every 360 requests), I was also wondering whether perhaps each request was causing more memory to be consumed, and after a limit is reached (perhaps out-of-memory error), all workers are killed, at which point there's a longer delay for workers to start/warm up.

Yohanna also suggested there could be some undocumented throttling, e.g. only so many requests over a time window.

**Comment by duncandewhurst** [comment]
Thanks both, are you doing any further investigation or shall I share that feedback with the publisher?

**Comment by yolile** [comment]
I implemented another retry strategy that seems to be working (https://collect.kingfisher.open-contracting.org/logs/kingfisher/portugal_releases/ec20e9da5a4611eb85470c9d92c523cb.log) but even if it works I think that you can share the feedback with the publisher (maybe including how ofter the errors occurs https://github.com/open-contracting/kingfisher-collect/issues/545#issuecomment-762768460 and https://github.com/open-contracting/kingfisher-collect/issues/545#issuecomment-762913855)

**Comment by yolile** [comment]
@duncandewhurst it worked! The collection ended successfully with all the data (1.153.001 pages)

**Comment by jpmckinney** [comment]
1. I think the number of retries and `wait_time` needs to go in the request meta. `CONCURRENT_REQUESTS_PER_DOMAIN` is 2 (and we might change it in future), so `number_of_retries` (renamed to `retries`) on the class will be shared by multiple requests, whereas we want one for each request. See Scrapy's RetryMiddleware's code, for example.
2. Are you sure we want to always raise DontCloseSpider in `spider_idle`? Won't that cause the spider to never close? The repo linked from the StackOverflow discussion suggests that it isn't necessary since Scrapy 1.0: https://github.com/ArturGaspar/scrapy-delayed-requests
1. I assume we still want `download_delay = 1, but just checking.

**Comment by duncandewhurst** [comment]
Feedback shared with publisher in CRM-6093
