### ISSUE TITLE
Kyrgyz Republic: Alternate URL?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#550]
**Links to bulk download and/or API documentation**
https://analytics.zakupki.gov.kg/api-export

It currently 404s; they are dealing with server issues, so please check periodically.

**Link to CRM issue**
CRM-6409

**Priority**
anytime

**Data structure**
not yet known

**Comment by jpmckinney** [comment]
Aha, if you access https://analytics.zakupki.gov.kg/dashboard/weekly (you can switch to English in top-right) and then click API & Export, you'll get the API endpoints (and docs) that were shared in the CRM issue. So, we can update the heredocs for the spider.

**Comment by yolile** [comment]
@jpmckinney is this issue just about updating the documentation or also adding a new spider?

**Comment by jpmckinney** [comment]
We can update the docs, and then also add the planning endpoint to the existing spider, e.g. http://ocds.zakupki.gov.kg/api/planning/171305565, which is documented at https://app.swaggerhub.com/apis/DPAteam/export-api-documentation/1.0

**Comment by jpmckinney** [comment]
Agreed with @yolile to just add a note to the docstring that the planning endpoint is not implemented for the reasons in CRM-6409

**Comment by nativaldezt** [comment]
Ok! Added
