### ISSUE TITLE
Consider including a GUI

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#556]
Should we include a simple GUI where the users who are not familiarized with the command line can select a spider and its parameters to run?

**Comment by jpmckinney** [comment]
We have a notebook that works as a GUI, right?

Users who aren't familiar with the command-line will still end up with up to thousands/millions of files, which such users probably can't handle. I think the OCDS registry is the better solution for less technical users.

Can you describe which users this GUI would be for?

**Comment by yolile** [comment]
> We have a notebook that works as a GUI, right?

Yes, but if you want to download a lot of files I think the google collab session will be closed.
But maybe the intermediate solution while the OCDS registry is ready, would be to export the notebook as a jupyter notebook and recommend the users to use it locally that way

**Comment by jpmckinney** [comment]
That sounds good to me!
