### ISSUE TITLE
indonesia_bandung: ModuleNotFoundError: No module named 'flattentool'

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#558]
**Which service is affected?**

Kingfisher Collect
http://collect.kingfisher.open-contracting.org

**What were you trying to do?**

Run the `indonesia_bandung` scraper:

```
curl -n http://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=indonesia_bandung -d note="Started by Duncan."
```

**What error did you receive?**

See [log](http://collect.kingfisher.open-contracting.org/logs/kingfisher/indonesia_bandung/9e09819e278811ebaad50c9d92c523cb.log).

**Did you attempt a fix?**

No

**How soon do you need a fix?**

ASAP - Ben asked today for an analysis of the Bandung data which needs to be done by tomorrow for translation into Bahasa.

**Comment by yolile** [comment]
@jpmckinney the flattentool requirement is indeed in the requirements.txt file https://github.com/open-contracting/kingfisher-collect/blob/9dde2cf8edb97e77136f008f42e86441316654b5/requirements.txt#L17 I deployed the service and restarted scrapyd but it still doesn't work, is there an extra step that should I do?

**Comment by jpmckinney** [comment]
I restarted with `./run.py 'kingfisher-process*' supervisord.restart scrapyd` and ran Duncan's `curl` command, and it's running with job ID 6b4c4f94281d11ebaad50c9d92c523cb

Log: http://collect.kingfisher.open-contracting.org/logs/kingfisher/indonesia_bandung/6b4c4f94281d11ebaad50c9d92c523cb.log

**Comment by jpmckinney** [comment]
Docs: https://ocdsdeploy.readthedocs.io/en/latest/deploy/kingfisher.html#restart-scrapyd
