### ISSUE TITLE
Update Chile Compra Spider to include new URLs

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#569]
CRM-6714

Chile Compra now publishes framework agreements and direct tenders too with different URLs:

Licitaciones: http://api.mercadopublico.cl/APISOCDS/OCDS/listaOCDSAgnoMes/2020/01/0/100

Convenio Marco:  http://api.mercadopublico.cl/APISOCDS/OCDS/listaOCDSAgnoMesConvenio/2020/01/0/100

Trato directo: http://api.mercadopublico.cl/APISOCDS/OCDS/listaOCDSAgnoMesTratoDirecto/2020/01/0/100

**Comment by jpmckinney** [comment]
@yolile If you put a hyphen like CRM-6714 it will autolink :)

**Comment by yolile** [comment]
@jpmckinney cool! Thank you, James, edited!
