### ISSUE TITLE
Peru Compras Spider

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#576]
**Links to bulk download and/or API documentation**
https://www.catalogos.perucompras.gob.pe/ConsultaOrdenesPub

**Links to bulk download and/or API endpoints**
https://www.catalogos.perucompras.gob.pe/ConsultaOrdenesPub

**Link to CRM issue**
CRM-6754

**Priority**
as soon as possible

**Data structure**
Valid OCDS 1.1 release packages

**Comment by nativaldezt** [comment]
The page creates the OCDS json in the client-side, in a javaScript function and requires click actions, so scrapy cannot be used. A proposal for this could be to use selenium as suggested in [here](https://stackoverflow.com/questions/6682503/click-a-button-in-scrapy).
![perucompras](https://user-images.githubusercontent.com/72802235/102800634-e6b77100-4392-11eb-8a1d-d32672debc49.png)

**Comment by yolile** [comment]
update: they will generate the JSON at the server-side instead

**Comment by yolile** [comment]
update: they generate the JSON at the server-side now, but the service is in their test server

**Comment by jpmckinney** [comment]
Does the test server have test data or real data?

If real data, should we change the spider to use the test server? I'm assuming this just involves changing one URL later.

**Comment by yolile** [comment]
It is real data in a test server, so we can develop the spider and change the URL later, indeed.

The test server URL is https://webqa.perucompras.gob.pe/ConsultaOrdenesPub/#

**Comment by yolile** [comment]
update: they are publishing in their production server now! https://www.catalogos.perucompras.gob.pe/ConsultaOrdenesPub
