### ISSUE TITLE
Support both rar and zip files in a single spider

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#590]
For example, the Dominican Republic portal has `rar` and `zip` files: https://www.dgcp.gob.do/datos-abiertos/estandar-mundial-ocds/.

- [x] Add functionality to support rar and zip files in a single scraper
- [x] Add that functionality to the Dominican Republic spider
- [ ] Update date filter to consider 2020 in Dominican Republic spider

**Comment by yolile** [comment]
closed by #602
