### ISSUE TITLE
Uganda: add financial year as date argument and update API domain

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#594]
Some countries have financial year or fiscal year formats in a year range as strings, for example '2019-2021' in [Uganda](https://docs.google.com/spreadsheets/d/10tVioy-VOQa1FwWoRl5e1pMbGpiymA0iycNcoDFkvks/edit). This allows to implement the date spider arguments as strings.

Update the API domain to https://gpppapi.com

**Comment by yolile** [comment]
I think we can use `from_date` and `until_date` (eg `from_date=2019` `until_date=2021`) as usual and the spider can parse both years with the endpoint specific format (eg joining both with -)

**Comment by aguilerapy** [comment]
That works if we want to download (`from_date='2017-2018'` `until_date='2019-2020'`) ?

Because if we enter (`from_date=2017` `until_date=2020`) how the spider can parse data from `'2016-2017'` and `'2020-2021'` ?

**Comment by yolile** [comment]
I think that is the exact logic that should be implemented in each spider. (eg building the URLs following the logic needed by each endpoint)

**Comment by yolile** [comment]
My preferred solution is to:
- Use the normal `from_date` and `until_date` parameters
- Set the default `from_date` and `until_date` for each affected spider
- Document that the year refers to fiscal year
- If `from_date=year` is set, download `[year-1 and year`] and [`year and year+1]` etc and document that as well.

What do you think @jpmckinney ?

**Comment by jpmckinney** [comment]
> If from_date=year is set, download [year-1 and year] and [year and year+1] etc and document that as well.

I think it's better if the logic is if `from_date=2018` searches only `2018-2019`.

Otherwise, I don't think it's possible to search a single fiscal year.

**Comment by aguilerapy** [comment]
The API stopped working: 

https://gpp.ppda.go.ug/adminapi/public/api/pdes
https://gpp.ppda.go.ug/adminapi/public/api/open-data/v1/releases/contract

**Comment by yolile** [comment]
The new API domain seems to be https://gpppapi.com/ now, as:

- https://gpppapi.com/adminapi/public/api/pdes and 
- https://gpppapi.com/adminapi/public/api/open-data/v1/releases/tender?fy=2020-2021&pde=818 (for example)
are working.
