### ISSUE TITLE
Check data encoding/load etc

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#616]
from https://github.com/open-contracting/kingfisher-collect/pull/609#issuecomment-780684094:

[I reviewed] how we use encode/decode/json.dump/json/load/bytes/str and I noticed a few things:

* [x] I see one case in `mexico_quien_es_quien` where JSON data is dumped then encoded to bytes, which I don't think is necessary. And, actually, I think that spider could just use `root_path` instead of indexing to the `'data'` key.

Otherwise, most of the relevant code is in `middlewares.py`:

* ResizePackageMiddleware dumps the package, but I don't think this is necessary (it's done by the extensions). However, we'd need to deepcopy the package metadata if we remove that line.
  * **Update:** Whether we dump it here or in FilesStore makes no difference. It's maybe a minor optimization in the case where the item is dropped before it reaches the extension. The current version is less complex than deepcopy.
* AddPackageMiddleware loads the data to add `{"releases":[...]}` around the data. Technically, we could just do this using an f-string if the input is a str or bytes.
  * **Update:** We can do this, but hand-editing JSON seems like something we should only do if this is a real performance bottleneck, which it is not.
* [x] LineDelimitedMiddleware decodes the bytes to str, but I don't remember why this behavior was introduced in https://github.com/open-contracting/kingfisher-collect/commit/7d406748a36cf073f2cff93a80c23c324324d6f2

Regex: `\b((en|de)code|json\.(dump|load)|bytes\b|json\(\)|ijson\.)`

**Comment by yolile** [comment]
> LineDelimitedMiddleware decodes the bytes to str, but I don't remember why this behavior was introduced in 7d40674

It come from the old `base_spider` code:
https://github.com/open-contracting/kingfisher-collect/blob/6c612837e998fb0ca166381ae4c596c898950b64/kingfisher_scrapy/base_spider.py#L261-L268

**Comment by jpmckinney** [comment]
Yes, but I'm not sure why it was there to begin with :) I linked to the commit that added the first version 7d40674

**Comment by yolile** [comment]
maybe from https://github.com/open-contracting/kingfisher-collect/issues/371#issuecomment-620095207 ?

**Comment by jpmckinney** [comment]
Aha. I'm not sure it's still needed.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting/kingfisher-collect/commit/d9b8fcc559ba61fdbc72d6e3ce1508e33fb33604
