### ISSUE TITLE
mexico_inai_portal: Change in access method

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#622]
I'm not sure how the original site worked, but there seems to be an API now: http://contratacionesabiertas.inai.org.mx/contratacionesabiertas/datosabiertos

Currently, submitting the web form in the current version returns a list containing PDFs.

**Comment by yolile** [comment]
as part of this, we should also remove `mexico_inai` (CRM-7009), update `mexico_inai_portal` to use this new API and rename it to `mexico_inai_api`
