### ISSUE TITLE
pakistan_ppra_api: Invalid JSON

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#645]
https://www.ppra.org.pk/api/index.php/api/record/442076 contains unescaped quote characters like:

> "description": "1. Corri pub on 29 Jan 21 against tender no. 16-0982-00 qty is amended"FOR" 216978 "READ" 127540. 2. Corri pub on 04 Feb 21 against tender no. 07-1317-5-00 Tender Delivery Period and opening date are amended. 3. Corri pub on 8 Feb 21 against tender no 16-0982-00 tender opening date is amended "FOR" 8 Feb 21 "READ"  1 Mar 21. 4. Corri pub on 12 Feb 21 against tender no. 02-1619-00 tender opening date is amended "FOR" 12 Feb 21 "READ" 19 Feb 21. 5. Corri pub on 12 Feb 21 against tender no. 01-1438-00 tender opening date is amended "FOR" 12 Feb 21 "READ" 23 Feb 21. 6. Corri pub on 18 Feb 21 against tender no. 02-1619-00 tender opening date is amended "FOR" 19 Feb 21 "READ" 26 Feb 21. 7. Corri pub on 24 Feb 21 against tender no. 07-1317-00 tender opening date is amended "FOR" 22 Feb 21 "READ" 02 Mar 21. 8. Corri pub on 26 Feb 21 against tender no. 16-0982-00 tender opening date is amended "FOR" 01 Mar 21 "READ" 15 Mar 21 . See more detail in attach file, please.",

It seems to all be `"FOR"` and `"READ"`, so we can maybe escape those quote characters and see if the rest works.

**Comment by nativaldezt** [comment]
I did an evaluation of all the JSONs and this is the list of errors that I got:
- Invalid control character '\t'
- Invalid control character '\n'
- Expecting ',' delimiter or '}'
- Expecting property name enclosed in double quotes

The total number of invalids JSON is 755.

e.g:
![image](https://user-images.githubusercontent.com/72802235/111649719-6662a980-87e3-11eb-8f84-8d1c15658a10.png)

![errorpakistan2](https://user-images.githubusercontent.com/72802235/111649474-2b607600-87e3-11eb-9363-27e5afd72e24.png)

![errorpakistan3](https://user-images.githubusercontent.com/72802235/111649490-2e5b6680-87e3-11eb-9600-523d42d30f2d.png)

So, I'm not sure how many cases we are going to solve by escaping "FOR" and "READ".

[pakistan_jsons_evaluation.xlsx](https://github.com/open-contracting/kingfisher-collect/files/6165131/pakistan_jsons_evaluation.xlsx)

**Comment by jpmckinney** [comment]
I'll mark as blocked. Please create or update a CRM issue so that the appropriate analyst can contact them about this.

**Comment by jpmckinney** [comment]
Removing blocked since we *could* skip the requests with bad JSON, but maybe not worth the effort.

**Comment by yolile** [comment]
CRM-6623
The API is down now

**Comment by odscrachel** [comment]
The API is back http://www.ppra.org.pk/api/index.php/api/release

**Comment by jpmckinney** [comment]
I've renamed this issue. This issue is for the API. The bulk download available at http://www.ppra.org.pk/api/index.php/api/release (spider pakistan_ppra_bulk) deserves a separate issue if it goes down again.
