### ISSUE TITLE
pluck: Using it to determine latest release date won't work with IndexSpider, PeriodicSpider

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#647]
We've made spider classes that are extremely efficient at scheduling requests. However, to determine the latest release date, the order of requests matters. Some options:

* Set from_date. For example, for MEL1 criteria, we can set it to the start of the year, since any date within the year is fine
* Stop yielding requests from `build_request` as soon as there is one without a callback

**Comment by yolile** [comment]
> Stop yielding requests from build_request as soon as there is one without a callback

Hmm, but for `IndexSpider` none of the requests has a callback:
https://github.com/open-contracting/kingfisher-collect/blob/89725b97555f16bbacb360647cc1c4aa82398eb1/kingfisher_scrapy/base_spider.py#L580-L581

**Comment by yolile** [comment]
Maybe we can stop yielding items there if `self.pluck`  instead?

**Comment by jpmckinney** [comment]
Yes, that's more or less what I meant :)
