### ISSUE TITLE
Mexico Plataforma Digital Nacional

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#651]
**Links to bulk download and/or API documentation**
https://plataformadigitalnacional.org/contrataciones

**Links to bulk download and/or API endpoints**
https://drive.google.com/file/d/1XOYDLVv-RqcMs8_hzkZ0fjC9FYh2psFw/view

**Link to CRM issue**
CRM-7014

**Priority**
as soon as possible

**Data structure**
Zip file with a > 2GB JSON array with releases

**Comment by jpmckinney** [comment]
`mexico_inai` interacts with Google Drive as well. Does that solution not work here?

**Comment by jpmckinney** [comment]
> @jpmckinney this points to a google drive big zip file, in order to be able to download the file we need a Google Drive API key, but I'm not sure if this API key should be an environmental variable or a spider argument, see #652 for the draft PR

If we do need an API key, then it should be an environment variable, like other authentication-related variables.

**Comment by yolile** [comment]
@jpmckinney I tried again using `https://drive.google.com` instead of `https://drive.google.com/u/0` and it works now without an API key

**Comment by yolile** [comment]
> mexico_inai interacts with Google Drive as well. Does that solution not work here?

Sadly not, because this file is much bigger, and for big files, google drive requires setting an API Key
