### ISSUE TITLE
Improve Spiders page

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#653]
- [ ] Clarify on the Spiders page that we are limited by the publisher’s API’s capacity
- [ ] Explain how the spiders are organized
- [ ] Explain why there are multiple spiders per country
- [ ] Make it clearer where we link to the source of the information
- [ ] Consider layout improvements to the Spiders page to make it easier to read/skim

Add guidance to:

- [ ] Select the appropriate spider (based on the Domain, whether bulk or API)
- [ ] Minimize the data to download (e.g. by start/end date)

**Comment by jpmckinney** [comment]
Closing as demand has not been renewed.
