### ISSUE TITLE
Add more links on documentation pages

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#654]
- [ ]  Check our documentation about checking the spider’s output, to see if it can be improved. Link to “Log files” from “Download data to your computer”
- [ ] Can link to relevant training materials, to join and flatten the files. 
- [ ] Link to the Spiders page more prominently from other pages
- [ ] Add link to issues labelled “existing spider” from Spiders page

**Comment by jpmckinney** [comment]
Closing as demand has not been renewed.
