### ISSUE TITLE
Improve individual spider documentation

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#655]
- [ ] See if some sources support greater concurrency (related #461)
- [ ] Note in the spider’s docstring if it is known to be slow (chile_compra_releases), and mention alternatives (eg bulk downloads)
- [ ] Auto-populate time range information in the documentation, based on the default from/until dates.
- [ ] Auto-generate a sentence, based on the data type to differentiate some spiders
- [ ] Link to the source’s website, if the user wants to look for alternatives.
- [x] Consider a clearer naming convention for spiders. (moved to #797)

**Comment by jpmckinney** [comment]
Noting that we could rename all the digiwhist spiders as part of this.

**Comment by yolile** [comment]
"Consider a clearer naming convention for spiders" is in a separate issue #797 now

**Comment by jpmckinney** [comment]
Closing as demand has not been renewed.
