### ISSUE TITLE
TenderBase.eu

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#661]
**Links to bulk download and/or API documentation**
?

**Links to bulk download and/or API endpoints**
http://www.tenderbase.eu/api/releases/?&page=0

**Link to CRM issue**
N/A

**Priority**
anytime

**Data structure**
JSON array of releases

**Comment by yolile** [comment]
The JSON result doesn't indicate the next page URL or the total number of pages. We can get the total number of releases from http://www.tenderbase.eu/releases/. But it is worth noting that the API takes longer to respond as the page number increase. Actually the last page http://www.tenderbase.eu/api/releases/?&page=54660 returns 502 Proxy error

cc @cecicasco

**Comment by jpmckinney** [comment]
I think we can finish the spider and see how far we can get.

**Comment by cecicasco** [comment]
Hi!!

I was working with this spider, and I want to know @yolile how do you know that 54660 is the last page, because if we take the number of the releases from http://www.tenderbase.eu/releases/ 559193

**Comment by yolile** [comment]
@cecicasco 54660 **was** the last page when I wrote the comment on March 23, they are probably just publishing more releases by now. So, As I mentioned: 

> We can get the total number of releases from http://www.tenderbase.eu/releases/

So the first step of the spider must be to get the total number of releases from that page.
