### ISSUE TITLE
Indonesia - opentender.net

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#673]
@yolile Indonesia Corruption Watch just shared their new OCDS publication in CRM-6782: https://opentender.net/#/ocds

They can't provide a single bulk file because of restrictions in their agreement with the national procurement authority. However, I'm assuming the download page as implemented would be particularly difficult to scrape.

Should we ask them to also provide a page with a list of download URLs for each LPSE (procuring entity)?

cc @jpmckinney

**Comment by jpmckinney** [comment]
I can't connect to that website (or with www. http://www.opentender.net). It might be temporarily down.

**Comment by yolile** [comment]
It works now, and I think that it will not be hard to scrape as we just need to:

- Call https://opentender.net/api/master/lpse?year={year} for each year to have the list of LPSE and then 
- Call https://opentender.net/api/tender/export-ocds-batch?year={year}&lpse={lpseid} for each year and LPSE id

**Comment by jpmckinney** [comment]
The LPSE codes are populated by https://opentender.net/api/master/lpse?year=2020

**Comment by duncandewhurst** [comment]
Great news. Thanks, @yolile!

**Comment by duncandewhurst** [comment]
In terms of priority, ICW's project with OCP ends at the end of March. It would be good to get them some feedback on the full dataset ASAP, so that they have time to address any issues before the end of the project.

Please can we prioritise writing the scraper so it is ready to run once they finished addressing my feedback in CRM-6782? Thanks!

**Comment by duncandewhurst** [comment]
Thanks for the speedy turnaround!

I ran the scraper again today and it returned some `zipfile.BadZipFile` and `JSONDecodeError` errors ([full list of errors](https://docs.google.com/spreadsheets/d/1rxrkTPFaWhFxUEc-VT1ltV9hMi1mAtjUGUcDQ89VE8s/edit?usp=sharing)).

I checked some of the links for which errors were reported and the files returned by the API are valid ZIP and JSON files, although I can see that the JSON files on the Kingfisher Collect server are indeed invalid.

I'm not sure whether the issue lies with the scraper, or whether there is an intermittent issue with the API. Do you have any ideas?

**Comment by duncandewhurst** [comment]
Update from ICW:

> Other errors than that seems to be related to ping timeout or incomplete downloads, when i retry they were successful. Maybe set the pause between pulls a bit more apart, or do something like 3x auto-retry on errors.

**Comment by jpmckinney** [comment]
Scrapy automatically does 3 retries. I think we can only either do more retries or wait longer.

**Comment by yolile** [comment]
> Scrapy automatically does 3 retries. I think we can only either do more retries or wait longer.

Hmm but Scrapy only retries for non 200 responses but in this case, I think that the problem is with partial downloads so I'm not sure if Scrapy will retry them

**Comment by duncandewhurst** [comment]
ICW fixed some issues, so I ran the scraper again. The only errors were HTTP errors this time, so no need to retry on the other error types for this spider right now. However, it could be a useful feature in general.

**Comment by duncandewhurst** [comment]
Latest update from the publisher on HTTP errors:

> most probably because data throttling of internet requests for anti-bot measures. please retry and give some pause between requests to avoid being banned from our ISP provider

How long does scrapy wait between requests and can we increase the wait time?

**Comment by yolile** [comment]
Yes, we can increase the wait time. Ideally, the publishers should communicate to the users how much time is needed between requests. But, according to the last [log](https://collect.kingfisher.open-contracting.org/logs/kingfisher/indonesia_opentender/22621f3a0b7911ec80dd0c9d92c523cb.log), I see that the errors were HTTP 500, which means internal server errors, for URLs such as https://opentender.net/api/tender/export-ocds-batch?year=2021&lpse=108 (that still gives me a 500 error), so I think the issue is with specific URLs rather than a throttling issue. @duncandewhurst  Could you send some of these URLs to the publisher to check, please? (feel free to re-open if the problem is actually with the spider)

**Comment by duncandewhurst** [comment]
Ah, I had already sent them but I will send again!

**Comment by duncandewhurst** [comment]
This spider isn't yielding any data. I checked the log and I can't see any errors: https://collect.kingfisher.open-contracting.org/logs/kingfisher/indonesia_opentender/12525e66216d11ec80dd0c9d92c523cb.log

I also checked the endpoints and they are working OK, e.g. https://opentender.net/api/master/lpse?year=2020 and https://opentender.net/api/tender/export-ocds-batch?year=2020&lpse=102 both return data.

**Comment by cecicasco** [comment]
Hi Duncan.. Let me check what is happening

**Comment by yolile** [comment]
@duncandewhurst It seems that they changed the "lpse" endpoint, and now we need to set an additional parameter to get the data in JSON format, eg https://opentender.net/api/master/lpse?year=2020&format=json. @cecicasco is already working on the fix

**Comment by duncandewhurst** [comment]
Great. Thanks, both! `curl` returned JSON without the parameter so I didn't realise something had changed.

**Comment by yolile** [comment]
@duncandewhurst the fix was merged and deployed

**Comment by duncandewhurst** [comment]
Thanks! The spider is running ok now :-)
