### ISSUE TITLE
Send data to an Amazon S3 bucket

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#700]
From CRM-7120, EdgeworthBox are interested in using Kingfisher Collect to send data to an Amazon S3 bucket.

They wanted to know if the tool supported any storage formats other than writing data to disk because their platform runs on a cloud-based solution without a local filesystem.

They seemed confident they could find a workaround but I'm logging this here in case it comes up again.

**Comment by jpmckinney** [comment]
It should be easy for them to replace the KingfisherFilesStore extension with something that uses boto3 to store on AWS. I assume they have developers?

**Comment by duncandewhurst** [comment]
Yep, I don't think it will be a problem. I offered a follow-up call in case they have further questions once they look into it.

**Comment by jpmckinney** [comment]
Can re-open if this is needed by more than one user.
