### ISSUE TITLE
Mexico IZAI

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#706]
**Links to bulk download and/or API endpoints**
https://contratacionesabiertas.izai.org.mx/contratacionesabiertas/datosabiertos

**Link to CRM issue**
https://crm.open-contracting.org/issues/6062

**Priority**
e.g. anytime

**Comment by aguilerapy** [comment]
Apparently, the data download is not working.

**Comment by yolile** [comment]
The URL that works is http://128.199.8.41:3000/edca/contractingprocess/null, so it seems that they link to fix something in their API documentation/domains

**Comment by jpmckinney** [comment]
Removing blocked label if we have a working URL.
