### ISSUE TITLE
Refactor test spiders

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#717]
After #707, we'll have two "fake" spiders, for which we have special logic in most commands. Two options:

1. Move the spiders out of `kingfisher_scrapy.spiders`. In our test code, change the `SPIDER_MODULES` setting.
2. Add a class attribute to the spiders, which can be checked in the commands.

I prefer 1 because it avoids any special logic in the commands.

**Comment by yolile** [comment]
Finally, we didn't need a new "fake" spider in #707

**Comment by jpmckinney** [comment]
It might still be nice to move the one fake spider, so that new commands don’t need to make an exception.

**Comment by jpmckinney** [comment]
It seems like we don't use the `fail` spider in any tests!

I've moved it. We can run it with: `scrapy crawl fail -s SPIDER_MODULES=tests.spiders`.

**Comment by jpmckinney** [comment]
Closed in b070720
