### ISSUE TITLE
Croatia

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#721]
**Links to bulk download and/or API documentation**
https://eojn.nn.hr/SPIN/application/ipn/Oglasnik/PreuzimanjeUgovoraOCD.aspx

The data is provided in monthly bulk files, is it possible to automate the download of all the data?

**Link to CRM issue**
CRM-7269

**Priority**
This week

**Data structure**
The latest file (March 2021) [passes the structure and format check](https://standard.open-contracting.org/review/data/1ea9abf8-2cb5-469c-a2f4-9aa238362391)

**Comment by yolile** [comment]
It should be possible and similar to https://github.com/open-contracting/kingfisher-collect/blob/main/kingfisher_scrapy/spiders/nigeria_portal.py

**Comment by duncandewhurst** [comment]
Great! I've updated the priority to 'this week', based on the update from Karolis in the CRM issue.

**Comment by yolile** [comment]
@duncandewhurst the spider was deployed and I started it already [here]( https://collect.kingfisher.open-contracting.org/logs/kingfisher/croatia/6911340ec27f11ebb6530c9d92c523cb.log).

**Comment by duncandewhurst** [comment]
Great, thanks!
