### ISSUE TITLE
uganda: implement retry logic for 429 errors

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#724]
Instead of increasing the download_delay, we can use the `DelayedRequestMiddleware` by doing something similar to uk_contracts_finder:
https://github.com/open-contracting/kingfisher-collect/blob/4265ea3808a0475ccbda9428d95fac35d799f020/kingfisher_scrapy/spiders/uk_contracts_finder.py#L27-L39

**Comment by jpmckinney** [comment]
I don't know if related, but there was a recent exception for Uganda in Sentry: https://sentry.io/organizations/open-contracting-partnership/issues/2419892921/?environment=production&project=5287294&referrer=alert_email

**Comment by cecicasco** [comment]
Hi! @jpmckinney Can we have access to the sentry? I was trying to look at the error but we don´t have access

**Comment by yolile** [comment]
@cecicasco Andres has access already and I've sent you an invite now

**Comment by aguilerapy** [comment]
Can you please send me the invitation again? I think I didn't confirm the invitation @yolile

**Comment by Ravf95** [comment]
@yolile I think we can mark this with "blocked" tag, because they have SSL problems.

**Comment by yolile** [comment]
Blocked until #837 is resolved

**Comment by jpmckinney** [comment]
Closing as both blocked and old.
