### ISSUE TITLE
nigeria_portal: Returns invalid JSON

### ISSUE THREAD

**Issue by pindec** [open-contracting/kingfisher-collect#728]
The NOCOPO portal seems to serve up invalid JSON e.g. [this file](http://nocopo.bpp.gov.ng/downloads.aspx?file=Exported/JSON/NocopoJson42441.json).

Last [scrape](https://collect.kingfisher.open-contracting.org/logs/kingfisher/nigeria_portal/5ef709f8c77a11ebb6530c9d92c523cb.log) retrieved 181 files, all of which have JSONDecodeErrors in Process (`collection_id` = 2164). 

Marking as blocked since we need the publisher to implement a fix (currently multiple OCDS release packages in one file, but not formatted as a valid JSON object or array). *Edit* publisher is actively working on their export (see [CRM ticket](https://crm.open-contracting.org/issues/7222#note-8)).

Once it's fixed we may need to update the spider.

**Comment by jpmckinney** [comment]
@yolile It looks like they're using concatenated JSON. I think we're able to handle this, so I removed the blocked label.

**Comment by yolile** [comment]
@pindec this should be fixed now, I started a new scrape [here](https://collect.kingfisher.open-contracting.org/logs/kingfisher/nigeria_portal/0c7b86dccf8f11ebbf200c9d92c523cb.log)

**Comment by jpmckinney** [comment]
I think the spider sometimes tries to parse HTML as JSON, though it otherwise looks good.

**Comment by pindec** [comment]
Great, thanks very much @yolile!
