### ISSUE TITLE
Some spiders create millions of files in a directory

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#740]
This creates performance issues on some filesystems. The approach taken by caching libraries is to generate and fill in arbitrary directory trees; if we take the same approach, there is existing code/libraries to reuse. Otherwise, we can consider other ways to segment files, which might be specific to those spiders that have a lot of files.

**Comment by yolile** [comment]
Note that this won't be an issue for some spiders after #944 anymore.

**Comment by jpmckinney** [comment]
For clarity, this issue is still relevant to some Digiwhist sources (line-delimited JSON).

**Comment by jpmckinney** [comment]
ProZorro actually hit the limit of files per directory (perhaps `max_dir_size_kb`), causing the (misleading) error message: `OSError: [Errno 28] No space left on device`

**Comment by yolile** [comment]
From a conversation with @jpmckinney:

Creating arbitrary (but predictable) directories is the best approach. 

Ruby on Rails’ FileStore does:
```
hash = Zlib.adler32(fname)
hash, dir_1 = hash.divmod(0x1000)
dir_2 = hash.modulo(0x1000)
```
And then formats the numbers dir_1 and dir_2 as "%03X"

`File.join(cache_path, DIR_FORMATTER % dir_1, DIR_FORMATTER % dir_2, fname)`

We could follow the same approach and also use adler32, as other existing hashing libraries for Python (such as hashlib) only return byte or hex strings and not integers.

We should implement this as part of the FilesStore extension and for all the existing spiders, to be consistent with the output.

**Comment by jpmckinney** [comment]
DatabaseStore's yield_items_from_directory probably needs to use glob instead of scandir.
