### ISSUE TITLE
Kaduna State Budeshi Spider

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#742]
**Links to bulk download and/or API endpoints**
https://www.budeshi.ng/kadppa/api

**Link to CRM issue**
CRM-7270

**Priority**
this week

**Comment by odscrachel** [comment]
Could we increase the priority level for this as there is in outstanding data review https://crm.open-contracting.org/issues/6597 . Thanks

**Comment by yolile** [comment]
@cecicasco thanks, @odscrachel the spiders are deployed now, (one for their releases and another one for their records) I started them both, check [here](https://collect.kingfisher.open-contracting.org/jobs).

**Comment by odscrachel** [comment]
Great, thanks @cecicasco & @yolile
