### ISSUE TITLE
Ebonyi State

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#746]
**Links to bulk download and/or API documentation**
https://ebonyieprocure.eb.gov.ng/ocds_report.php

**Links to bulk download and/or API endpoints**
https://ebonyieprocure.eb.gov.ng/ocds_report.php

**Link to CRM issue**
CRM-6785

**Priority**
anytime

**Data structure**
Releases packages

**Comment by Ravf95** [comment]
The release package file **media_ocds2019.json** has a json structural errors. The errors are in **line 8429** which is `"rationale": " selective tendering"`, and **line 8446** which is `"procurementMethodRationale": " selective tendering"` both lines contain one tab value in field value.
