### ISSUE TITLE
Add custom URL filters

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#749]
We already support query string params filters with [qs](https://kingfisher-collect.readthedocs.io/en/latest/local.html#filter-the-data). However, there are some APIs like [Colombia](https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/#!/releases/findByFilters) and [Dominican Republic](http://148.101.176.123:48080/ocdsdr/docs#operation/ReleasesByProcurementMethod_api_v1_releases_byProcurementMethod__procurementMethod__get) where the API doesn't use query params but path params for additional filtering. We could add a `qp` or `ps`  (for query param string) option where the user can specify the path param and its value if any.

**Comment by jpmckinney** [comment]
We can do `pc` (path component), but instead of `arg=value` like `qs`, it should just be all the components, e.g. `arg/value1/value2`, since there's no standard way to construct path parameters.
