### ISSUE TITLE
Ghana Records

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#751]
**Links to bulk download and/or API documentation**
https://www.ghaneps.gov.gh/ocds/report/home.action#/recordPackages

**Links to bulk download and/or API endpoints**
https://www.ghaneps.gov.gh/ocds/report/home.action#/recordPackages

**Link to CRM issue**
CRM-7378

**Priority**
e.g. next week

**Data structure**
record packages

**Comment by duncandewhurst** [comment]
It looks like the same endpoints as Zambia exist, e.g. https://www.ghaneps.gov.gh/ocds/services/recordpackage/getrecordpackagelist

**Comment by cecicasco** [comment]
Yes! I just figured out it now looking for some examples
