### ISSUE TITLE
Base class for INAI's API spiders

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#760]
We can write a base class for all the spiders that use the INAI platform as API:

- [x] mexico_durango_idaip
- [x] mexico_guanajuato_iacip
- [x] mexico_inai_api
- [x] mexico_yucatan_inaip
- [x] mexico_zacatecas_izai
- [x] mexico_veracruz_ivai
- [x] mexico_inai_infoem

The base should contain:
- the `get_formatter` method
- root_path = 'arrayReleasePackage.item'
- date_format = 'year'
- data_type = 'release_package'

**Comment by Ravf95** [comment]
Hi @yolile. I think we can also use the INAI base class in [Mexico Veracruz spider](https://github.com/open-contracting/kingfisher-collect/pull/765).

**Comment by Ravf95** [comment]
We can also add [this](https://github.com/open-contracting/kingfisher-collect/issues/776) spider too to inherit the INAI base class

**Comment by yolile** [comment]
closed by #777 and #778
