### ISSUE TITLE
Edo State 

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-collect#761]
**Links to bulk download**
http://edpms.edostate.gov.ng/ocds/ 'Download JSON format' button on left menu

**Link to CRM issue**
[CRM-7308](https://crm.open-contracting.org/issues/7308)

**Priority**
today

**Data structure**
release package

**Comment by pindec** [comment]
Note that the releases array in the data currently contains planning release data objects, but also numbered keys with tender, award and contract releases as values. We will feed this back to the publisher.
