### ISSUE TITLE
Update colombia Spider

### ISSUE THREAD

**Issue by cecicasco** [open-contracting/kingfisher-collect#764]
They had add a Firewall, so we can´t download all the releases at once, the actual spider uses the API with date range with start_date in 2011, the we suggest to use the API that download per year to avoid the blocking

**Links to bulk download and/or API documentation**
https://apiocds.colombiacompra.gov.co:8443/apiCCE2.0/#/

**Link to CRM issue**
[CRM-7368](https://crm.open-contracting.org/issues/7368)

**Priority**
e.g. as soon as possible

**Comment by yolile** [comment]
I don't see how using another endpoint will resolve the issue. They always return only 100 releases per page, no matter the endpoint. If this is a firewall problem, shouldn't we implement a rate limit instead? Do we know their rate limit? The previous logs don't show any errors, eg HTTP 429 codes or similar, therefore, I'm not sure about the problem nor the solution.

**Comment by cecicasco** [comment]
They suggest a meeting with the people in carge of the infra by their side, maybe we can do that

**Comment by yolile** [comment]
As part of this, we should update the API URL to: https://apiocds.colombiacompra.gov.co/apiCCE2.0/

I tested their API now and https://apiocds.colombiacompra.gov.co/apiCCE2.0/rest/releases?page=1 gives me 504, but https://apiocds.colombiacompra.gov.co/apiCCE2.0/rest/releases/page/2021?page=1 is working, so we could indeed try to implement this instead if we haven't had any news from them.

**Comment by cecicasco** [comment]
Hi! I was working on this spider and I get an error of time out in  [this](http://apiocds.colombiacompra.gov.co/apiCCE2.0/rest/releases/page/2021?page=2&_id=6062227230a615007ff246d9) that is references as the next link in [this](http://apiocds.colombiacompra.gov.co/apiCCE2.0/rest/releases/page/2021?page=2&_id=6062227130a615007ff24220)


How should we deal with the error?

**Comment by yolile** [comment]
@cecicasco That means the service is not working as expected and we cannot use that one either. Could you please reach out to Colombia Compra again and ask them how we can use the API to get all the data as the `next` links are not working?

**Comment by cecicasco** [comment]
> @cecicasco That means the service is not working as expected and we cannot use that one either. Could you please reach out to Colombia Compra again and ask them how we can use the API to get all the data as the `next` links are not working?


Hi! The Issue in the CRM is [#7548](https://crm.open-contracting.org/issues/7548)

**Comment by yolile** [comment]
I updated the spider (https://github.com/open-contracting/kingfisher-collect/commit/0ea29f4bac3930f5ca383aba7128564c86bc1391, https://github.com/open-contracting/kingfisher-collect/commit/247e4ad1bf8409258a2f85539f0b622b7a5efc82, https://github.com/open-contracting/kingfisher-collect/commit/3ae39e54ad6b0a7eec7c1433708f9eeafc05d7a2) to use the new URL and date arguments always, they also increased their server time out, so the spider is working correctly now

**Comment by jpmckinney** [comment]
So the API is only reliable when dates are provided?

**Comment by yolile** [comment]
It also works without date parameters, but it is faster with them. I can add a comment in the spider to clarify

**Comment by jpmckinney** [comment]
Let's add a comment - that way we don't need to find the reason in this issue :)
