### ISSUE TITLE
Cross River State (Nigeria)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#766]
**Links to bulk download and/or API documentation**
http://ocds.dppib-crsgov.org/calabar/dashboard/records

**Links to bulk download and/or API endpoints**
http://18.202.236.131:8101/records/json-download/recordPackage_2020_2_1

The bulk download URLs seem to follow a consistent pattern:

http://18.202.236.131:8101/records/json-download/recordPackage_[year]_[month]_1

**Link to CRM issue**
CRM-7426

**Priority**
This week

**Data structure**
Structurally valid, with some additional fields: https://standard.open-contracting.org/review/data/9cec7d9f-dd5c-4ca7-a63f-cc33f8e7ab2a

**Comment by cecicasco** [comment]
Hi! I was working in this spider but for now the service is down :( I will continue when it is up again

**Comment by duncandewhurst** [comment]
Yes, it seemed to be quite up-and-down when I was looking at it. I've left the publisher know in CRM-7426

**Comment by duncandewhurst** [comment]
The publisher made some changes to the portal. The new URL is http://ocds.dppib-crsgov.org/ReleasePackageViewModel_ListView/

Please could you check if it's possible to automate the download of all the data using this page? I can no longer get the download URLs with the Firefox Web Developer Tools, but I may be missing something!

**Comment by duncandewhurst** [comment]
The publisher made some more changes - there are now endpoints for monthly release and record packages:

http://ocdsapi.dppib-crsgov.org/api/ocdsAPI/getRecordPackage?year=2020&month=4

http://ocdsapi.dppib-crsgov.org/api/ocdsAPI/getReleasePackage?year=2020&month=4
