### ISSUE TITLE
Anambra State (Nigeria)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#767]
**Links to bulk download and/or API documentation**
http://www.mepbdp.org.ng/ocds/api

**Links to bulk download and/or API endpoints**
The project list endpoint is broken, so you need to use the [mda_list](http://www.mepbdp.org.ng/ocds/api/mda_list) and [mda_records](http://www.mepbdp.org.ng/ocds/api/mda_records) endpoints. It looks like another Budeshi implementation.

**Link to CRM issue**
n/a - found whilst Google searching another Nigerian state!

**Priority**
Anytime

**Data structure**
Looks good! https://standard.open-contracting.org/review/data/db1f2f95-9c4b-43ab-9494-5b24c59fe071

**Comment by cecicasco** [comment]
Hi! @duncandewhurst The [mda_records](http://www.mepbdp.org.ng/ocds/api/mda_records) does not work, and I don´t get how we can use the [mda_list](http://www.mepbdp.org.ng/ocds/api/mda_list) to get the list of project. Can you clearify to me that ?

**Comment by duncandewhurst** [comment]
Ah, sorry I should've been clearer. You need to add the `id` from the mda_list endpoint to the end of the mda_records endpoint, e.g. http://www.mepbdp.org.ng/ocds/api/mda_records/1

**Comment by cecicasco** [comment]
Oh Cool.. I gonna try that way! Thanks

**Comment by cecicasco** [comment]
Hi! the side is down, do you have any news?
