### ISSUE TITLE
Update Nigeria Cross River Spider

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/kingfisher-collect#775]
In [this](https://github.com/open-contracting/kingfisher-collect/pull/774) pull we discussed reimplement the spider to get the available months and years from [here](http://ocds.dppib-crsgov.org/ReleasePackageViewModel_ListView/) for request only the available dates. This feature requires a scraper from ASP.NET programmed page.

**Link to github issue**
#766

**Priority**
anytime

**Comment by yolile** [comment]
blocked due to https://github.com/open-contracting/kingfisher-collect/pull/786#issuecomment-910888903

**Comment by Ravf95** [comment]
The publisher made changes, now we have API endpoint http://ocdsapi.dppib-crsgov.org/api/ocdsAPI/getAvailableReleasesSummary for request available dates
