### ISSUE TITLE
Rewrite 'Writing spiders' page

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-collect#78]
things to look out for when writing / testing new sources:

- errors while running
- warnings from framework
- test data, see check output
- the biggest thing I've noticed is that it's really easy to accidentally download the same thing over again, or download loads of stuff we don't actually need

It's just we say to people "test this" and sometimes it's not clear what that encompass.

**Comment by jpmckinney** [comment]
We should mention which request meta keys are reserved: https://docs.scrapy.org/en/latest/topics/request-response.html?highlight=dont_redirect#request-meta-special-keys
