### ISSUE TITLE
UKContractsFinder: Upgrade to v2 of API

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#787]
https://www.contractsfinder.service.gov.uk/apidocumentation/V2

**Comment by cecicasco** [comment]
Hi! I was reading the documentation of V2 of API, I cannot find the API releated to OCDS

**Comment by jpmckinney** [comment]
Huh, I guess they haven't re-implemented the OCDS endpoints in V2...

> Contracts Finder API is updating. Version 2 of the API attempts to improve the structure and standardise approaches to aid the user in posting and retrieving notices. For more details, please visit Version 2.
