### ISSUE TITLE
KenyaMakueni: Can't use IndexSpider

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#788]
The count endpoint returns the number of results *on that page* not in the dataset.

For example, https://opencontracting.makueni.go.ke/api/ocds/release/count?pageSize=1 returns 1 🙃 

The default `pageSize` is 300, so we were always getting 300 from https://opencontracting.makueni.go.ke/api/ocds/release/count

Right now, there are fewer than 1000, so we can get all the data by increasing the pageSize to 1000 (the maximum), but once they exceed 1000 releases we will need a new strategy, so we should implement it now.

**Comment by Ravf95** [comment]
I saw the issue with @aguilerapy we think we can use the `SimpleSpider` class
and iterate and count over `https://opencontracting.makueni.go.ke/api/ocds/release/count?pageNumber=<page++>&pageSize=1000` until the request return 0 
for later use the max counted pages to iterate again over
`https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=<page>`

another method is iterate and request only `https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1&pageNumber=<page++>` until them return 0

```
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=0
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=1
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=2
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=3
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1000&pageNumber=4
.
.
.
https://opencontracting.makueni.go.ke/api/ocds/package/all?pageSize=1&pageNumber=665
```

what do you think?

**Comment by jpmckinney** [comment]
I think just paginate over the `/all` endpoint (second method) but use `pageSize=1000`, not `1`.
