### ISSUE TITLE
Implement a retry logic for incomplete/partial downloads

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#794]
I tried to scrape Indonesia Corruption Watch's recently updated publication and Kingfisher Collect reported ~100 JSONDecodeErrors and zipfile.BadZipFile errors ([error list](https://docs.google.com/spreadsheets/d/18hn4Y5j_CQfWwFeC1mLzZhsBEkD6Tg_jAdDNZJO8GVo/edit#gid=143130050), [log](https://collect.kingfisher.open-contracting.org/logs/kingfisher/indonesia_opentender/22621f3a0b7911ec80dd0c9d92c523cb.log)).

I checked a few examples and the server returns valid files, so this looks like the same problem with partial downloads discussed in https://github.com/open-contracting/kingfisher-collect/issues/673#issuecomment-809849580 onwards.

I will report the issue to the publisher but it would be good if Kingfisher Collect could handle this type of problem.

**Comment by duncandewhurst** [comment]
I'm still seeing lots of `JSONDecodeError`s with the ICW scraper. As above, when checking the URLs the errors were reported for, the server returns valid files, so it looks an issue with incomplete/partial downloads. Was the linked PR supposed to address the `JSONDecodeError`s or only the `BadZIPFile` errors?

Here's an example error:

index | collection_id | warnings | errors | count | example_filenames | example_urls
-- | -- | -- | -- | -- | -- | --
1 | 2472 |   | JSONDecodeError('Extra data: line 1 column 68644 (char 68643)',) | 3 | export-ocds-batch-year-2016-lpse-98-ocds-data-tender-02112021114214.json,export-ocds-batch-year-2018-lpse-308-ocds-data-tender-02112021134623.json,export-ocds-batch-year-2018-lpse-307-ocds-data-tender-02112021134623.json | https://opentender.net/api/tender/export-ocds-batch?year=2018&lpse=307,https://opentender.net/api/tender/export-ocds-batch?year=2016&lpse=98,https://open

Let me know if you need any more information.

**Comment by jpmckinney** [comment]
Those files are somehow corrupted, e.g. (see the issue around `onType`):

```
rah Kabupaten Jayawijaya", "id": "D347"}}]}onType": "tender", "ocid": "ocds-20h3g7-1913098", "tag": 
```

when I run:

```
head -c 68700 20211102_020106/export-ocds-batch-year-2016-lpse-98-ocds-data-tender-02112021114214.json | tail -c 100
```

The API is not consistent. You can download https://opentender.net/api/tender/export-ocds-batch?year=2016&lpse=98 multiple times, and each time the filename within the ZIP is different.

At any rate, these JSON files are inside ZIP files, and ZIP files have checksums to guarantee file integrity. So, the invalid JSON was generated on their server. This isn't something Collect can fix.

**Comment by yolile** [comment]
> Was the linked PR supposed to address the JSONDecodeErrors or only the BadZIPFile errors?

Only `BadZIPFile` errors, because Kingfisher Collect only decompresses the files, without reading them. We could start reading the JSON files in Kingfisher Collect and retry de download if a `JSONDecodeError` is raised (deleting the already decompressed JSON file first and then retrying the download X times), but maybe that is just too much

**Comment by jpmckinney** [comment]
I think that’s too much. We focus on the HTTP layer in Collect (recovering from 500 errors etc). There needs to be a point where it’s up to the publisher to fix their publication.

Duncan: what percentage of files have JSON errors?

**Comment by duncandewhurst** [comment]
Ah, I see. Thanks! That explains why the server return valid files for the examples that I checked. From the discussion in #673 I'd understood that the JSONDecode errors were also related to partial downloads. Given that the problem is with how the files are generated, I agree that we don't need to handle it in Collect.

~3% of files have errors, which accounts for ~100k releases based on the size of the last collection without errors.

I'll share the feedback with the publisher.
