### ISSUE TITLE
Gombe State (Nigeria)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#805]
**Links to bulk download and/or API documentation**
http://gombe.stateopencontracting.com/Other-Basic/Report/Json-Report

**Links to bulk download and/or API endpoints**
http://gombe.stateopencontracting.com/Other-Basic/Report/Json-Report

The publisher reuses the [Nocopo](http://nocopo.bpp.gov.ng/OpenData.aspx) platform, so it should be possible to reuse the `nigeria_portal` spider.

**Link to CRM issue**
CRM-7572

**Priority**
Anytime

**Data structure**
The data is structurally valid with the exception of some invalid codes.

@jpmckinney @yolile the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria) so you can add it to the data registry.

**Comment by Ravf95** [comment]
Yes, the new spider can reuse the `NigeriaPortal class`.
I think we can create a base class for Nigeria Portal and Gombe State, another option for Gombe State is to use `NigeriaPortal class` as a base class and modify the `start_requests` method for it. @yolile what do you think?

**Comment by yolile** [comment]
Let's create the spider without using any base class for now, and then create a follow-up issue to create a base class and refactor the existing spiders to use it.
