### ISSUE TITLE
Spider not found errors

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#806]
Collect returns an error when I try to run either the `nigeria_cross_river_records` or `nigeria_cross_river_releases` spiders:

```
curl -n https://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=nigeria_cross_river_records -d note="Started by Duncan for CRM-7426."
{"status": "error", "message": "spider 'nigeria_cross_river_records' not found"}
```

```
curl -n https://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=nigeria_cross_river_releases -d note="Started by Duncan for CRM-7426."
{"status": "error", "message": "spider 'nigeria_cross_river_releases' not found"}
```

It looks like the naming changes discussed in https://github.com/open-contracting/kingfisher-collect/issues/797 have been deployed to the server but the documentation hasn't been updated.

**Comment by yolile** [comment]
Thanks for reporting @duncandewhurst, this is now fixed https://kingfisher-collect.readthedocs.io/en/latest/spiders.html#kingfisher_scrapy.spiders.nigeria_cross_river_state_records.NigeriaCrossRiverStateRecords
