### ISSUE TITLE
Update Mexico INAI's spiders

### ISSUE THREAD

**Issue by aguilerapy** [open-contracting/kingfisher-collect#819]
Some portals have added data from 2021, such as [mexico_veracruz_ivai](http://187.216.225.247:3000/edca/contractingprocess/2021) and [mexico_yucatan_inaip](https://captura.contratacionesabiertas.inaipyucatan.org.mx/edca/contractingprocess/2021), but the spider has `default_until_date = 2020`. 

Should we remove `default_until_date` for this and all the others? If we search for a [empty year](https://captura.contratacionesabiertas.inaipyucatan.org.mx/edca/contractingprocess/2022), it returns 404.

- [ ] mexico_durango_idaip
- [ ] mexico_guanajuato_iacip
- [ ] mexico_mexico_state_infoem
- [ ] mexico_mexico_city_infocdmx
- [ ] mexico_nuevo_leon_cotai
- [ ] mexico_oaxaca_iaip
- [ ] mexico_quintana_roo_idaip
- [ ] mexico_veracruz_ivai
- [ ] mexico_yucatan_inaip
- [ ] mexico_zacatecas_izai

**Comment by jpmckinney** [comment]
Yes, let's remove the `default_until_date` and change the logic to stop at either the current year, or on 404.

**Comment by jpmckinney** [comment]
I think we just need to set `start_requests_callback` to a method that will ignore the 404, instead of yielding a FileError (since we are expecting the 404). We should still log the 404 for debugging, though.

**Comment by yolile** [comment]
I guess the most correct option is to get the available years by scraping the API documentation eg http://www.infoem.org.mx:4000/contratacionesabiertas/datosabiertos and then build the URLs on the available years. That implies changing INAI Base to stop extending from Periodic Spider and including that logic there. (and removing both, `default_from_date` and `default_until_date` from all the spiders)

**Comment by jpmckinney** [comment]
Oof, I don't like the idea of scraping HTML if we can avoid it. That page seems to call this (undocumented?) API though: http://infoem.org.mx:3000/edca/fiscalYears, which returns:

```json
{"fiscalYears":[{"id":3,"year":2021,"status":true,"createdAt":"2021-08-02T10:43:09Z","updatedAt":"2021-08-02T10:43:09Z"}]}
```

**Comment by yolile** [comment]
Woohoo even better, let's use that service then
