### ISSUE TITLE
Ekiti State (Nigeria)

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/kingfisher-collect#831]
**Links to bulk download and/or API documentation**
https://ocds.bpp.ekitistate.gov.ng/Home/Procurements

**Links to bulk download and/or API endpoints**
https://ocds.bpp.ekitistate.gov.ng/Home/Procurements

**Link to CRM issue**
[CRM-7237](https://crm.open-contracting.org/issues/7237)

**Priority**
as soon as possible

**Data structure**
Check if the data is at least close to be structurally valid against OCDS

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please inform Yohanna and/or James to add it to the data registry.*

**Comment by yolile** [comment]
> I see the pagination were made with DataTables. I'm not sure if we can iterate over the pages using only scrapy.

Actually, it seems the pagination is made at the client-side, so all the content is already on the page, we will just need to scrape the page to get the ocids (sorry @jpmckinney I think we don't have another option here), and then call the endpoint that you found
