### ISSUE TITLE
`nigeria_edo_state` no longer available (2023)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#834]
https://edpms.edostate.gov.ng/ocds/bulkjson.php returns a query error

CRM-7308

**Comment by yolile** [comment]
The download is back online 🎉  see CRM-7308#note-52

**Comment by yolile** [comment]
And now, https://edpms.edostate.gov.ng/ocds/bulkjson.php returns (60) SSL certificate problem or Internal Server Error

**Comment by yolile** [comment]
Now the spider is working again (with a warning): 

`2022-02-03 14:18:35 [scrapy.core.downloader.tls] WARNING: Remote certificate is not valid for hostname "edpms.edostate.gov.ng"; VerificationError(errors [DNSMismatch(mismatched_id=DNS_ID(hostname=b'edpms.edostate.gov.ng'))])`

**Comment by jpmckinney** [comment]
Can we switch it to `http`?

**Comment by yolile** [comment]
Yes, we can, but not sure if we want to keep `https` and wait for them to fix the certificate issue

**Comment by jpmckinney** [comment]
I think better to avoid a warning. The likelihood that someone performs a man-in-the-middle attack in order to falsify the information is low. I think there's higher risk that we see the SSL issue degrade into an error.
