### ISSUE TITLE
Add "has sample mode" option per source

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-collect#84]
This is needed for #207 - none of the Digiwhist Sources have sample modes.

When someone tries to run a Source in Sample mode that has no Sample, ignore this and show a nice message to them instead.

This is particularly important for when people run "run --all --sample"

(from discussion with @duncandewhurst )

**Comment by jpmckinney** [comment]
I had a quick look, and this indeed still needs to be done, i.e.:

* each spider can have a class variable that indicates whether it supports sampling (if we add more CLI options in the future, we might want to use something other than a long series of variables)
* if a spider doesn't support sampling and `--sample` is provided, then error. Alternately, show a message saying sampling isn't supported, and don't set the collection's sample to true.

207 refers to https://github.com/open-contracting/kingfisher/issues/207 (issue had been moved between repositories)

**Comment by odscjames** [comment]
We can maybe pause this at the moment tho - before this was important because someone might have run "run --all --sample" expecting a small download for each.

But with the new system there isn't currently a way to run all at once, and when we set one up we can make sure it works well in sample mode or non-sample mode. Depending on how the new run-all options works, that may alter the best technical way to achieve this.

**Comment by jpmckinney** [comment]
I think we can perhaps have a global solution that uses `CLOSESPIDER_ITEMCOUNT` to close the spider once the sample size has been met.

**Comment by odscjames** [comment]
> I think we can perhaps have a global solution that uses CLOSESPIDER_ITEMCOUNT to close the spider once the sample size has been met.

I would be wary of this because the number of items being small is only one thing of several I think people would expect on activating a sample mode. They would also expect that their machine would only download a reasonable amount of data. Under a global CLOSESPIDER_ITEMCOUNT scheme, someone trying to get a sample of France's Digiwhist data will still download 1GB.

**Comment by jpmckinney** [comment]
digiwhist_base presently downloads the entire file, then breaks after a given number of lines. This issue isn't about making those per-spider improvements. I've opened a new issue about streaming a download so that we can gunzip only part of it: #312

**Comment by jpmckinney** [comment]
Since Scrapy can in some cases send many requests before the CLOSESPIDER_ITEMCOUNT is reached, what we can do (either in addition to using CLOSESPIDER_ITEMCOUNT, or as an alternative) is add an item pipeline with a high priority that counts the number of items it has seen and then raises DropItem for any further items. (We might want to not count FileError items.)

If we're doing this as an alternative to CLOSESPIDER_ITEMCOUNT, then the new pipeline will have to close the spider.

**Comment by jpmckinney** [comment]
> Since Scrapy can in some cases send many requests before the CLOSESPIDER_ITEMCOUNT is reached, what we can do (either in addition to using CLOSESPIDER_ITEMCOUNT, or as an alternative) is add an item pipeline with a high priority that counts the number of items it has seen and then raises DropItem for any further items. (We might want to not count FileError items.)

This is what Yohanna did for the LatestReleaseDate feature – and it works! 😃

**Comment by jpmckinney** [comment]
> This is what Yohanna did for the LatestReleaseDate feature – and it works! 😃

Actually, maybe we can just set `CONCURRENT_ITEMS` to 1?

**Comment by yolile** [comment]
I was trying to update the settings in the base `from_crawl` method, but due to what is explained [here](https://github.com/scrapy/scrapy/issues/1305) it is not working, so I think that we need to do what the issue says and override the `CloseSpider` class.

The other option is to use `-s CLOSESPIDER_ITEMCOUNT=1 -s CONCURRENT_ITEMS=1` directly instead of `-a sample=true` but I think these are too many parameters

**Comment by jpmckinney** [comment]
Hmm, I don't know `-s CLOSESPIDER_ITEMCOUNT=1 -s CONCURRENT_ITEMS=1` seems okay to me.

Is the `sample` feature even used that often? I think it's okay to have to copy-paste a bit more if it's not used much.

**Comment by jpmckinney** [comment]
Hmm, looks like using both together probably wasn't going to guarantee we only process one item anyway: https://stackoverflow.com/questions/59130988/limit-number-of-retrieved-items-with-scrapy

So, we'll have to add a `Sample` item pipeline like for `LatestReleaseDate`, which drops items once the `CLOSESPIDER_ITEMCOUNT` is reached.

We can maybe extract the logic for counting items from `LatestReleaseDate` into this new pipeline. The `self.processed` logic in `LatestReleaseDate` essentially tests for `CLOSESPIDER_ITEMCOUNT=1` via presence of the spider name in a set. We can have more generic logic that tests for whatever number is set by `CLOSESPIDER_ITEMCOUNT`.
