### ISSUE TITLE
Split base_spider.py into separate files

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#845]
Under a `kingfisher_scrapy.base_spiders` module.

**Comment by yolile** [comment]
Should we also move some publisher-specific base classes into this new module? Or at least some of them, for example, `digiwhist_base` or `mexico_inai_base` which are used by multiple spiders

**Comment by jpmckinney** [comment]
Hmm, we have 14 of those (`find kingfisher_scrapy/spiders -name '*_base.py'`). I think it is better to leave them in proximity to the spiders.
