### ISSUE TITLE
Enugu State new spider

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-collect#852]
**Links to bulk download**
https://dueprocess.en.gov.ng/ocds_report.php

**Link to CRM issue**
[CRM-7680](https://crm.open-contracting.org/issues/7680)

**Priority**
anytime

**Data structure**
Passes DRT

**Comment by odscrachel** [comment]
I'll close this issue as the bulk download is currently giving data for a different state, I'll reopen when this is fixed.

**Comment by odscrachel** [comment]
Bulk downloads now available here: https://dueprocess.en.gov.ng/ocds_report.php

**Comment by Ravf95** [comment]
@yolile I think we can parse the list of files with a selector and then download them. It's the same case as #831 because the [site](https://dueprocess.en.gov.ng/ocds_report.php) uses [DataTables](https://datatables.net/) too.

**Comment by odscrachel** [comment]
I tried to run this spider today using the following command 

> curl -n https://collect.kingfisher.open-contracting.org/schedule.json -d project=kingfisher -d spider=nigeria_enugu_state -d note="Started by Rachel" steps=check,compile 

and got the following error

> {"status": "error", "message": "spider 'nigeria_enugu_state' not found"}

**Comment by jpmckinney** [comment]
I've redeployed and run the command. The spider is now running.

Note that you're missing a `-d` before `steps=check,compile` - not sure if this is an error in documentation somewhere?

**Comment by odscrachel** [comment]
Great, thanks and not to worry, `-d` was my omission. Although as a side note, I don't think the check command is in the [deploy docs](https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-collect.html#collect-data) yet.

**Comment by jpmckinney** [comment]
All good - we'll update the docs as part of #861
