### ISSUE TITLE
Change default to skip checks

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#861]
Originally, Collect was used primarily to give feedback to publishers, in which case it made sense to check the data by default in Process. (Collect passes the desired steps to Process.)

Now, we often use Collect to perform analyses, where we don't care about or even look at the check results.

Since the check step is very slow, unnecessary checks from analysis collections interfere with the needed checks for feedback collections.

I propose that we change checks to "opt-in" so that analysts get their results quicker without extra effort.

@yolile Can you check with ODS and CDS if they agree?

cc @duncandewhurst as this relates to your Slack message.

**Comment by yolile** [comment]
> @yolile Can you check with ODS and CDS if they agree?

The consensus was that it is ok to not run the checks as default as long as there is a way to start the checks manually in case they forget to set the argument when starting the spider

**Comment by jpmckinney** [comment]
Once done, update deploy docs to document `-d steps=check,compile` https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-collect.html#collect-data

**Comment by yolile** [comment]
@ndrhzn @fppenna @allakulov @Camilamila do you agree with the proposed approach? That is, do not compile and run checks by default while scheduling crawls in Kingfisher Collect

**Comment by jpmckinney** [comment]
I think you mean do not run checks, and compile by default.

**Comment by jpmckinney** [comment]
> The consensus was that it is ok to not run the checks as default as long as there is a way to start the checks manually in case they forget to set the argument when starting the spider

Noting that the way to start checks manually is: https://ocdsdeploy.readthedocs.io/en/latest/use/kingfisher-process.html#add-structural-checks

**Comment by fppenna** [comment]
I think it is fine, we can just add `-d steps=check,compile` when needed.

**Comment by allakulov** [comment]
Yes - agreed, provided that we retain the option to run checks
