### ISSUE TITLE
Base classes: consider declaring base class attributes in the base class

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#863]
Right now we don't declare any class attributes in base classes, for example, we don't set `data_type` in `SimpleSpider`. If a subclass doesn't set this variable, an error will occur only when running the spider, but while coding it, an editor won't detect that a variable is missing in the sub-class. We can consider changing this by defining the variable in the base class with: 

```` python
  @property
  def data_type(self):
      raise NotImplementedError
````

When declaring the variable this way, the missing variable in the sub-class will be raised at the definition time already, and not only at running time. 

The other option is: 

```` python
data_type: str = NotImplemented
````

This is more elegant but it also works at running time only. Scrapy, for example uses in the `Spider` class: 

```` python
    name: Optional[str] = None
    custom_settings: Optional[dict] = None
````

But these two variables are not required but optional.

**Comment by jpmckinney** [comment]
We could also add a test that checks for required attributes.

> When declaring the variable this way, the missing variable in the sub-class will be raised at the definition time already, and not only at running time.

But:

```
python

class Foo:
    @property
    def bar():
      raise NotImplementedError

Foo()
# No error
```

**Comment by yolile** [comment]
> But:

The same happens with the current approach anyway. 
The advantage of the proposed approach is to be warned by your IDE (that is at definition time) that there are some properties that the sub-class needs to implement, eg: 
![image](https://user-images.githubusercontent.com/6834122/142619368-4f4d5c6b-3154-4e38-838d-7c066e65876e.png)


And in the base class, the IDE will not complain anymore about having a not defined variable, eg
![image](https://user-images.githubusercontent.com/6834122/142618922-54ffa6fc-b278-4a73-bee3-02407ef488a9.png)

**Comment by jpmckinney** [comment]
Aha, assuming the developer uses such an IDE. (I use Sublime Text.) Does CDS use such IDEs?

**Comment by aguilerapy** [comment]
I use PyCharm

**Comment by Ravf95** [comment]
I use PyCharm too

**Comment by yolile** [comment]
Closing as this is IDE dependent and we add tests when checks are required.
