### ISSUE TITLE
Update spiders metadata for Mexico Nuevo León

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/kingfisher-collect#864]
The publisher changes its name to "La Secretaría de Movilidad y Planeación Urbana de Nuevo León" (previously  "La Secretaría de Infraestructura de Nuevo León").

**Link to CRM issue**
[7827](https://crm.open-contracting.org/issues/7827)

**Related spiders**
- [ ] mexico_nuevo_leon_records
- [ ] mexico_nuevo_leon_releases

**Comment by yolile** [comment]
Closed by #865 #866
