### ISSUE TITLE
Spiders' from_crawler exceptions are not being logged

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#868]
None of the exceptions raised in Spider's `from_crawler` methods are being logged. For example when running `scrapy crawl colombia_ani_records -a sample=asds` the output is https://collect.kingfisher.open-contracting.org/logs/kingfisher/colombia_ani_records/38ca0a504d3a11ec90ee0c9d92c523cb.log, with no further logging after the exception is raised (in this case the expected exception is https://github.com/open-contracting/kingfisher-collect/blob/60da8f1ef6c6bd66fab186beebe27eaf67df65b0/kingfisher_scrapy/base_spider.py#L182). 

I tried locally by deactivating the RetryMiddleware https://github.com/open-contracting/kingfisher-collect/blob/60da8f1ef6c6bd66fab186beebe27eaf67df65b0/kingfisher_scrapy/spidermiddlewares.py#L214 just in case, and also downgrading Scrapy, without any luck.

**Comment by jpmckinney** [comment]
To find the use of all our exception classes, we can use this regex: `KingfisherScrapyError|SpiderArgumentError|MissingEnvVarError|AccessTokenError|MissingNextLinkError|UnknownArchiveFormatError|IncoherentConfigurationError`

Some of these are raised in spider callbacks, and they should probably instead raise `CloseSpider`: https://docs.scrapy.org/en/latest/topics/exceptions.html

For the rest, I'd like to know (or test) whether Scrapy doesn't log any unhandled exceptions, or only when the exception is raised in `from_crawler`. If the latter, then we can add a method to log a message and then raise an error. If the former, then we can add a spider middleware to log the exception and then re-raise it.

----

I checked, and we are using Scrapy's own errors in appropriate locations:

- `DropItem` in `process_item`
- `StopDownload` in `bytes_received`
- `IgnoreRequest` in downloader middlewares
- `NotConfigured` in extensions' `from_crawler` (Scrapy documents this as only allowed in `__init__`, but its own middlewares, extensions, etc. also raise it in `from_crawler`)
- `NotSupported`
- `UsageError` in commands (not documented)

We don't yet use:

- `CloseSpider` in spider callbacks (so far we only need to close the spider from downloader middlewares or the item pipeline, from which we need to instead call `crawler.engine.close_spider()`)
- `DontCloseSpider` in `spider_idle`

The regex is `DropItem|StopDownload|IgnoreRequest|NotConfigured|NotSupported|UsageError|CloseSpider|DontCloseSpider`

**Comment by yolile** [comment]
Hmm, I remember that these errors were logged in the past, but from what you are mentioning I checked the history and saw that we used to use `CloseSpider` but then we changed that in https://github.com/open-contracting/kingfisher-collect/commit/76a6344d273204664625391d9adaf6c53a72947f. I guess we need to go back to `CloseSpider` in `from_crawlers` then

**Comment by jpmckinney** [comment]
We can just change the exception inheritance to avoid rewriting lots of files.

**Comment by jpmckinney** [comment]
In my testing, raising CloseSpider from `__init__` has the same effect as our own exceptions (no logging), so we need to follow one of the alternatives.

**Comment by yolile** [comment]
Yes, that is true, I was testing the same. And actually, `base_class` always have used the `SpiderArgumentError` exception. What I see from the mentioned commit is that for some of them we used to raise the exception and log the issue eg with `spider.logger.error('KINGFISHER_PARAGUAY_DNCP_REQUEST_TOKEN is not set.')`, maybe that is why I remember that at least something was being logged

**Comment by yolile** [comment]
Maybe we can do: 

```` python
class KingfisherScrapyError(Exception):
    def __init__(self, error):
        spider.logger.error(error)

?

**Comment by yolile** [comment]
> For the rest, I'd like to know (or test) whether Scrapy doesn't log any unhandled exceptions, or only when the exception is raised in from_crawler.

For exceptions that are in the spiders methods, for example, `parse_list` in https://github.com/open-contracting/kingfisher-collect/blob/e0c3ad66bfa1730c16284da30ea6201926f04f8b/kingfisher_scrapy/spiders/india_civic_data_lab.py#L41, I tested with manually setting `data['truncated'] = True` and the exception was raised and logged.

**Comment by jpmckinney** [comment]
I think once the spider is running, Scrapy logs errors, but if it's raised in `__init__`, we need to do like your suggestion. I'll subclass `KingfisherScrapyError`, since we don't need to log for all subclasses.

**Comment by jpmckinney** [comment]
Re: `CloseSpider`, I think we moved away from it, because it was better for KingfisherProcess to not consider the spider to be "closed" if an error was raised.

I think the Kingfisher Process integration is smarter now (I think it checks the "reason" for the closure), but anyway, just raising an error is safest.
