### ISSUE TITLE
Add spider for Ecuador SERCOP

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/kingfisher-collect#880]
**Links to bulk download and/or API documentation**
https://datosabiertos.compraspublicas.gob.ec/PLATAFORMA/datos-abiertos/api

**Priority**
anytime

**Data structure**
Check if the data is at least close to be structurally valid against OCDS

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please inform Yohanna and/or James to add it to the data registry.*

**Comment by yolile** [comment]
I think we can use the bulk downloads instead, which has the format: 

https://datosabiertos.compraspublicas.gob.ec/PLATAFORMA/download?type=json&year={year}&month={month}&method=all

We can use the `PeriodicSpider` base class in this case, with the default `from_year=2015,` as documented on their site.

**Comment by Ravf95** [comment]
> I think we can use the bulk downloads instead, which has the format:
> 
> [https://datosabiertos.compraspublicas.gob.ec/PLATAFORMA/download?type=json&year={year}&month={month}&method=all](https://datosabiertos.compraspublicas.gob.ec/PLATAFORMA/download?type=json&year=%7Byear%7D&month=%7Bmonth%7D&method=all)
> 
> We can use the `PeriodicSpider` base class in this case, with the default `from_year=2015,` as documented on their site.

I also used CompressedFileSpider base class because the files are compressed
