### ISSUE TITLE
Consider validating JSON files

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#897]
Some publications contain broken JSON files. Currently, if that broken JSON goes to Kingfisher Process, the entire process fails, and no further files are processed.

We could log and drop these broken files in Collect, maybe as part of the `Validate` pipeline. We don't want to perform the expensive task of parsing JSON files in all the publications; we can make that validation opt-in and only enable it for known spiders with broken data.

The advantage of this is that Kingfisher Process will receive only well-formatted JSONs for sure. so the process should finish without errors, but with some missing data. The missing data should be checked in Kingfisher Collect logs' and reported to the publisher.

**Comment by yolile** [comment]
This is relevant for the data registry, as right now, if a publication contains at least 1 invalid JSON, the entire publication is out from the registry. If we implement this, we need to make a note in the publication's quality section in the registry, so users are aware that some data will be missing.

**Comment by jpmckinney** [comment]
As I understand, "the entire process fails, and no further files are processed" only in the old version of Kingfisher Process.

In the new version of Kingfisher Process, processing continues, but I think maybe it is never considered "complete".

As such, the next statement is true, because the registry won't continue past the "process" task.

> if a publication contains at least 1 invalid JSON, the entire publication is out from the registry

I think maybe we want to edit Kingfisher Process rather than Collect.

**Comment by jpmckinney** [comment]
I think it's fine for Collect to write the same JSON file as delivered by the publisher. In most cases, the error is truncation or misquoting. A user might still find the file useful, and/or might be willing to make the effort to correct it.

If a user doesn't want the invalid file, they can do the same as we would (skip it).
