### ISSUE TITLE
nigeria_ebonyi_state: Contains literal TAB character `\t`, which is invalid JSON

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#901]
Like https://github.com/open-contracting/kingfisher-collect/pull/878, we should replace `'\t'` with `r'\t'` in the response text.

**Comment by Ravf95** [comment]
I suggest remove it, some JSON files contain tab characters outside the strings. I think another option is to search patterns like `(?<=\:).*(?<=\t)` (value that contains one or more tab char from key-value pairs)
