### ISSUE TITLE
`nigeria_cross_river_state_*` times out in the server (2024-07)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#905]
https://ocdsapi.dppib-crsgov.org/api/ocdsAPI/getAvailableReleasesSummary
https://ocdsapi.dppib-crsgov.org/api/ocdsAPI/getRecordPackage?year=2021&month=6

**Comment by jpmckinney** [comment]
Seems to be working again. Can you confirm and if so, close and update MEL1?

**Comment by yolile** [comment]
They are working indeed, and I've counted them in the past MEL check, I just forgot to close this issue, thanks!

**Comment by yolile** [comment]
Not working again

**Comment by yolile** [comment]
It works again now (but they don't have new data)

**Comment by yolile** [comment]
Not working again (same time out error)

**Comment by yolile** [comment]
Working again
