### ISSUE TITLE
nigeria_budeshi_* return errors

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#907]
https://budeshi.ng/Api returns Connection refused
http://budeshi.ng/Api works

CRM-7277

**Comment by yolile** [comment]
Ah but then http://budeshi.ng/api/releases/15393/planning, http://budeshi.ng/api/record/15393 and similar return 500 :(

**Comment by jpmckinney** [comment]
Some non-OCDS endpoints work:

* https://budeshi.ng/api/project_list
* https://budeshi.ng/api/mda_list

These all 500:

```fish
curl -sS https://budeshi.ng/api/mda_list | jq .[].id
for i in (seq 112)
  curl -sSI https://budeshi.ng/api/mda_records/$i | head -n 1
end
```

```fish
for i in (curl -sS https://budeshi.ng/api/project_list | jq .[].id)
  curl -sSI https://budeshi.ng/api/record/$i | head -n 1
  curl -sSI https://budeshi.ng/api/releases/$i/tender | head -n 1
end
```

Noting that the API docs have a typo (`relases`). `release` (singular) returns a 404 page (status code is 200 though).
