### ISSUE TITLE
peru_compras: Contains literal LF character `\n` within string, which is invalid JSON

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#909]
A newline character within a string needs to be escaped (`\\n`).

However, newlines can occur both within strings and at ends of lines, so unless we write a custom parser, it's not easy to escape only the newline characters within strings.

I guess we can replace `\n` with a single space.

**Comment by Ravf95** [comment]
I think the invalid JSON happens by the sequence of CR LF characters (&#x0d \n) within strings, this pattern take place in some strings. Also, some JSON files contain LF characters at end of lines.
