### ISSUE TITLE
Kenya PPRA 

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/kingfisher-collect#912]
**Links to bulk download and/or API documentation**
https://tenders.go.ke/Contracts

FYI, The first 'OCDS{JSON}' button doesn't give the bulk download data but if you view a particular contract then press the the same 'OCDS{JSON}' botton it gives a bulk download for the chosen year. 

**Link to CRM issue**
[CRM-6806](https://crm.open-contracting.org/issues/6806)

**Priority**
Regular

**Data structure**
[DRT results](https://standard.open-contracting.org/review/data/96f7b291-736e-46c0-b957-073e49d7435e)

**Comment by yolile** [comment]
> FYI, The first 'OCDS{JSON}' button doesn't give the bulk download data but if you view a particular contract then press the the same 'OCDS{JSON}' botton it gives a bulk download for the chosen year.

We can add this as a Caveat in the spider documentation

**Comment by Ravf95** [comment]
I think we can't handle this with scrappy. The download is done by onclick event, and the json data is generated by the `exportToJson` function (defined in [Contracts.js](https://tenders.go.ke/static/js/Pages/Configurations/Contracts.js)).

I saw these API endpoints:
- financial years list (release packages)
  - GET: https://tenders.go.ke/api/contract/all/0
- witch `{"financialyr": "years"}` payload
  - POST: https://tenders.go.ke/api/TenderDisplay/Submit/ID/financialyr
  - POST: https://tenders.go.ke/api/contract/Submit/ID/financialyr
  - POST: https://tenders.go.ke/api/bidders/Submit/ID/financialyr

So, I think we can suggest a new API endpoint, same payload as the others, to get release packages by financial years.

@yolile what do you think?

**Comment by yolile** [comment]
Oh yes. They are transforming the data from the different `*/financialyr` endpoints to OCDS in the browser with JavaScript 😞  @odscrachel I think we cannot count them as a publisher yet as we cannot download all the data automatically due to the issue described above. Could you report back this to the publisher again? As @Ravf95 mentioned, ideally, they should implement a new endpoint that returns the data in OCDS already. Thanks!

**Comment by jpmckinney** [comment]
This new spider has been blocked for over a year, so closing. (They still generate OCDS on the fly.)

**Comment by yolile** [comment]
Reopening as they finally have revamped their website and now they have proper bulk downloads https://tenders.go.ke/ocds (among other improvements to their website) 🎉 

To get the list of files they have https://tenders.go.ke/api/ocds/index?search=&perpage=10&sortby=&order=asc&page=1
(we can use next_page_url to iterate) and then https://tenders.go.ke/api/ocds/tenders?download=true&ocds_id={data/id} to download each file 

cc @allakulov
