### ISSUE TITLE
Honduras SEFIN Bulk download

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#913]
**Links to bulk download and/or API documentation**
https://www.sefin.gob.hn/edca/

**Links to bulk download and/or API endpoints**
Bulk download https://www.sefin.gob.hn/edca/
API https://guancasco.sefin.gob.hn/EDCA_WEBAPI/swagger/ui/index (the API endpoints return 500)

**Priority**
anytime

**Data structure**
Zip files with a JSON Line file with one release package per line

**Publication format**
Zip files with a JSON Line file with one release package per line

**Comment by Ravf95** [comment]
I think we can scrape this with one of these methods.

1. We can iterate over https://piep.sefin.gob.hn/edca/ocid_sefin_., with a year between 2012 and current year, and format can be CSV or zip.

2. We can send the form data as a payload (multipart/form-data or application/x-www-form-urlencoded) to https://www.sefin.gob.hn/wp-admin/admin-ajax.php?action=get_wdtable&table_id=163 (POST method), later we can parse the response.

form data as url decoded
```
draw=1&columns[0][data]=0&columns[0][name]=nombrearchivo&columns[0][searchable]=true&columns[0][orderable]=false&columns[0][search][regex]=false&columns[1][data]=1&columns[1][name]=chkmd5&columns[1][searchable]=true&columns[1][orderable]=false&columns[1][search][regex]=false&columns[2][data]=2&columns[2][name]=link1&columns[2][searchable]=true&columns[2][orderable]=false&columns[2][search][regex]=false&columns[3][data]=3&columns[3][name]=link2&columns[3][searchable]=true&columns[3][orderable]=false&columns[3][search][regex]=false&columns[4][data]=4&columns[4][name]=link3&columns[4][searchable]=true&columns[4][orderable]=false&columns[4][search][regex]=false&columns[5][data]=5&columns[5][name]=fecha&columns[5][searchable]=true&columns[5][orderable]=false&columns[5][search][regex]=false&start=0&length=-1&search[regex]=false&wdtNonce=43e5debaa8
```

 response looks like
```
	"draw": 1,
	"recordsTotal": "11",
	"recordsFiltered": "11",
	"data": [
		[
			"2022",
			"16c15ebd389826b35cfa68c864e6559bd66ee9c6",
			"<a data-content=' Ver' href='https:\/\/piep.sefin.gob.hn\/edca\/ocid_sefin_2022.zip ' rel='' target='_blank'> Ver<\/a>",
			"<a data-content=' Ver' href='https:\/\/piep.sefin.gob.hn\/edca\/ocid_sefin_2022.md5 ' rel='' target='_blank'> Ver<\/a>",
			"<a data-content=' Ver' href='https:\/\/piep.sefin.gob.hn\/edca\/ocid_sefin_2022.csv ' rel='' target='_blank'> Ver<\/a>",
			"09\/02\/2022 12:00 AM"
		], ...
```

**Comment by yolile** [comment]
Sure, and you can implement the API spider as well.
