### ISSUE TITLE
nigeria_plateau_state

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#931]
**Links to bulk download and/or API documentation**
https://plateaustatebpp.com/ocds

**Links to bulk download and/or API endpoints**
Looks similar to other Nigerian states.

**Link to CRM issue**
N/A

**Priority**
anytime

**Data structure**
Not checked

**Publication format**
Not checked

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*
Not checked

**Comment by yolile** [comment]
The site is not working anymore, error: `Could not resolve host: plateaustatebpp.com`

**Comment by yolile** [comment]
THe site is working again
