### ISSUE TITLE
psycopg2 dependency uninstallable on some systems

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-collect#932]
I was trying to set up kf-collect locally and encountered an error when installing requirements in that `psycopg2` wasn't available from pip3.

System specs:

* Debian 11
* Python 3.9.2
* pip 20.3.4 (ran as `pip3`)

I solved the issue for my system by manually installing `psycopg2-binary` from pip, and commenting out `psycopg2` in `requirements.txt`. I've successfully run kf-collect after that, no perceivable problems.

From searching, this [might also be a problem on macOS](https://stackoverflow.com/questions/49811955/unable-to-install-psycopg2-pip-install-psycopg2). Popular *nix distributions derived from Debian (Ubuntu, Linux Mint) may also be affected.

Suggest:
* consider changing the dependency to `psycopg2-binary` if feasible
* or adding documentation for the workaround described above, if not.

**Comment by jpmckinney** [comment]
We need psycopg2 for the installation on the server. But yes, this is a known issue, which we've solved in some other repos by having a different requirements file that uses psyscopg2 binary. We can do that here then.

**Comment by jpmckinney** [comment]
I've made two changes which should resolve the issue. Let me know if you still have the same problem after trying again in a fresh virtual environment.
