### ISSUE TITLE
new spider for Wales

### ISSUE THREAD

**Issue by odscjen** [open-contracting/kingfisher-collect#946]
**Links to bulk download and/or API documentation**
Should be the same underlying technology as PCS, so the same as the Scotland spider

**Links to bulk download and/or API endpoints**
https://api.sell2wales.gov.wales/v1?lang=en

**Link to CRM issue**
TBA

**Priority**
as soon as possible please

**Data structure**
Not checked

**Publication format**
Not checked

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*

**Comment by Ravf95** [comment]
Yes, @odscjen this spider is the same as the Scotland spider, and the spider has the same issue (some packages don't have release data, only package metadata, e.g https://api.sell2wales.gov.wales/v1/Notices?dateFrom=12-2021&noticeType=56&outputType=0), so maybe we can check it with them, anyway, I'll solve it with the same fix that uses Scotland spider (showing error in log and not saving the file)

**Comment by odscjen** [comment]
@Ravf95 that's great thank you!

**Comment by yolile** [comment]
@odscjen the spider is now available as `united_kingdom_wales`  and note that scotland name was changed to `united_kingdom_scotland`. And please remember that if the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9). thanks!
