### ISSUE TITLE
Nigeria Lagos State

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#949]
**Links to bulk download and/or API documentation**
https://lagosppaocds.azurewebsites.net/

**Links to bulk download and/or API endpoints**
https://lagosppaocds.azurewebsites.net/

**Link to CRM issue**
None

**Priority**
anytime

**Data structure**
Not checked

**Publication format**
Not checked, but the portal has the same format as Ekiti State.

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*

**Comment by Ravf95** [comment]
@yolile @jpmckinney  Do we know more about the e-gp provider? I think it's the same as the Ekiti State, so we can probably create a subclass for them

**Comment by jpmckinney** [comment]
It's a European Dynamics SaaS system. I think it operates differently from `EuropeanDynamicsBase`. We can call the new one `EuropeanDynamicsSaasBase`.
