### ISSUE TITLE
Nigeria Kano State

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-collect#950]
**Links to bulk download and/or API documentation**
N/A

**Links to bulk download and/or API endpoints**
https://kano-eproc.eurodyn.com/epps/home.do
https://kano-eproc.eurodyn.com/ocds/report/home.action#/records
https://kanoppb.org.ng/

**Link to CRM issue**
[CRM-8270](https://crm.open-contracting.org/issues/8270)

**Priority**
In the next few weeks would be great. Mid-august.

**Data structure**
Data appears to be OCDS Records

**Publication format**
Claims to be records but [downloads as a release](https://standard.open-contracting.org/review/data/717fac43-34f7-4eb2-afd5-352b93a2cfbf) (sample data copied and pasted from the "View" menu option)

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*

**Comment by Ravf95** [comment]
They're using [EuropeanDynamics](https://github.com/open-contracting/kingfisher-collect/blob/main/kingfisher_scrapy/spiders/european_dynamics_base.py) to publish record packages, also the compiled release and versioned release can be downloaded as separate files.

**Comment by yolile** [comment]
@mrshll1001 this is deployed now, please remember that *If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).* thanks!
