### ISSUE TITLE
`nigeria_anambra_state_records` invalid JSON

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-collect#957]
Scrapes return 0 rows, attempting to use the URL via the browser (Firefox) results in "Deceptive site warnings". Kingfisher Collect logs indicate DNS issues.

**Comment by yolile** [comment]
The URL is now https://eprocure.bpp.an.gov.ng/awarded_contracts.php and the implementation is the same as `nigeria_osun_state`

**Comment by jpmckinney** [comment]
Re-opening (instead of creating new issue) as their JSON is invalid: `"amount": ,`

**Comment by jpmckinney** [comment]
Still an issue, e.g. `"amount": 221,000,000.00 ,`

I suspect they manually construct JSON.

**Comment by jpmckinney** [comment]
New quality issue: They have amounts like `"amount": N230000000`.

**Comment by jpmckinney** [comment]
I think the same vendor does `nigeria_osun_state`, which has invalid JSON like `"quantity": LOT,`.
