### ISSUE TITLE
Panama DGCP API

### ISSUE THREAD

**Issue by Ravf95** [open-contracting/kingfisher-collect#961]
**Links to bulk download and/or API documentation**
https://ocds.panamacompraencifras.gob.pa/swagger/index.html

**Links to bulk download and/or API endpoints**
https://ocds.panamacompraencifras.gob.pa/swagger/index.html

**Link to CRM issue**
[CRM-8371](https://crm.open-contracting.org/issues/8371)

**Priority**
e.g. as soon as possible

**Comment by Ravf95** [comment]
I reopen this issue because the record and release spider fails when the page doesn't work (HTTP 500) (e.g [this page](https://ocds.panamacompraencifras.gob.pa/Record?page=657)).

So, I think the better way is to use IndexSpidex class instead of LinksSpider class, also ask the publisher why the API fails

**Comment by yolile** [comment]
Hmm, that page is working for me now. The only difference between using the `next` URL with `LinkSpider` and `IndexSpider` is that we keep `&DescendingOrder=true` with `IndexSpider.` And even setting that parameter #965 remains. So I'm not sure if this changes anything.

**Comment by jpmckinney** [comment]
In general, IndexSpider is preferred to LinksSpider, because it's better to schedule all requests at once. Then, we can control the concurrency through the scheduler, if needed.
