### ISSUE TITLE
nigeria_osun_state, nigeria_enugu_state returns incomplete JSONs

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#963]
[Senty issue](https://sentry.io/organizations/open-contracting-partnership/issues/3616401875/?referrer=alert_email&alert_type=email&alert_timestamp=1663968890791&alert_rule_id=7248661&environment=production)

**Comment by jpmckinney** [comment]
Also enugu: https://sentry.io/organizations/open-contracting-partnership/issues/3616401875/?project=5857059
