### ISSUE TITLE
panama_dgcp_records yields hundreds of records with duplicate OCIDs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#965]
Please check this quality issue. If it persists, need to update quality summary in data registry. (The duplicates are not included in the data downloads – which is only an issue if the duplicates differ.)

**Comment by Ravf95** [comment]
I'll check the pattern of the duplicated ocids (quickly check that the last record is duplicated on the next page)

**Comment by jpmckinney** [comment]
Is the last record always duplicated, or does this only happen when the first page gets a new record, and all subsequent records are "shifted" onto a new page?

**Comment by yolile** [comment]
> Is the last record always duplicated, or does this only happen when the first page gets a new record, and all subsequent records are "shifted" onto a new page?

From a manual test, it is the later (the records are shifted)

**Comment by jpmckinney** [comment]
How frequently does the API update? I think there were about 1000 duplicate OCIDs. The API has 8172 pages: https://ocds.panamacompraencifras.gob.pa/Record Either the API is very slow, or they add new OCIDs frequently.

**Comment by Ravf95** [comment]
Real time (ETL uses push events from the main portal)

**Comment by yolile** [comment]
And the API is slow, almost 20 seconds per page at the moment.

**Comment by jpmckinney** [comment]
Okay - then things are working as expected. Kingfisher Process will just warn about the duplicates, but will not process them twice. Thank you for investigating!
