### ISSUE TITLE
italy_anac yields ~1.5k releases without OCIDs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-collect#966]
Please check this quality issue. If it persists, need to update quality summary in data registry. (Releases without an OCID are not included in the data downloads.)

**Comment by yolile** [comment]
Noted in CRM-8077

**Comment by jpmckinney** [comment]
Still an issue (per Sentry for registry).

**Comment by yolile** [comment]
I've updated the registry quality section now. Do we want to keep this issue open?

**Comment by jpmckinney** [comment]
I guess not. It does cause warnings in Kingfisher Process that are reported to Sentry, but I'll see what I can do next time it happens.
