### ISSUE TITLE
united_kingdom_contracts_finder_base: Update for changes to search API response format

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-collect#968]
Related to CRM-8406.

Both `united_kingdom_contracts_finder_releases` and `united_kingdom_contracts_finder_records` are broken because the `/Search` endpoint now returns a release package, rather than an array of release packages nested under `results`, as expected by:

https://github.com/open-contracting/kingfisher-collect/blob/9a1c40eab52ebc8fc43b6361f48abe07f0f864f6/kingfisher_scrapy/spiders/united_kingdom_contracts_finder_base.py#L34

Please can the spider be updated as a priority as this issue is causing a problem for a partner's production system.

**Comment by yolile** [comment]
Done, besides that:
- The Search endpoint uses the Links extension now. Could you check if the releases returned by this endpoint are the same as the ones returned by the Release endpoint? (If so, we won't need to request the Release endpoint for each release returned by the Search endpoint)
- The release endpoint returns a release package
- The record endpoint returns a record package
- They don't use deprecated fields anymore, as far as I can tell, so they are publishing OCDS 1.1 now!

**Comment by yolile** [comment]
Reopening as we are not able to get all of their data. I think that maybe they are having a similar problem as FTS had https://github.com/open-contracting/kingfisher-collect/issues/877.

Besides that, the spider uses the `Search` endpoint to get the releases ids, and ocids to call the `Release` and `Record` endpoints. However, we are getting 404 errors when retrieving some releases, which is weird. 

@odscjen could you check this with the publisher?

**Comment by odscjen** [comment]
email sent to the publisher via [CRM#8421](https://crm.open-contracting.org/issues/8421)

**Comment by odscjen** [comment]
We're not the only people who have contacted them about issues with the API. Some fixes are being deployed tonight so I'll check again tomorrow to see if those sort the issue.

**Comment by jpmckinney** [comment]
To report to the publisher: They have invalid JSON (unescaped double quotes in values).

e.g. https://www.contractsfinder.service.gov.uk/Published/Notices/OCDS/Search?limit=100&publishedFrom=2014-01-01T00:00:00&publishedTo=2022-10-25T07:58:18&cursor=cHVibGlzaGVkRnJvbT0yMDE0LTAxLTAxVDAwOjAwOjAwfHB1Ymxpc2hlZFRvPTIwMjItMTAtMjVUMDc6NTg6MTh8bGltaXQ9MTAwfG5leHRDdXJzb3I9MzQ3ODIz

line 14351 column 610

```json
                "description": "A Further Competition from the dynamic purchasing system KMCSS-014  for the Provision of Internal Training Services to procure a provider to work with Kirklees Council, to provide continuous professional development and group supervision sessions for our internal pool of coaches.  The contract will initially run for a period of three (3) years up to 31st March 2023 with the option to extend the contract by up to a maximum of one (1) further twelve (12) month period.\r\n\r\nAdditional information: \r\nProposals were invited by the Council of the Borough of Kirklees (the "Council") from shortlisted Capable Delivery Partners currently on Category 3 - Coaching of the Council's Dynamic Purchasing System for the provision of internal training services.(REF: KMCSS-014).  The Dynamic Purchasing System Documentation is available to access at :https://www.yortender.co.uk/procontract/supplier.nsf",
```

**Comment by yolile** [comment]
Yeap, noted in CRM-8421#note-5

**Comment by duncandewhurst** [comment]
For those watching this issue who don't have access to the CRM, there are still some issues with the API. The helpdesk is working with the publisher to resolve them.

**Comment by yolile** [comment]
Now we managed to download all their data, so closing this issue. (CRM-8421)
