### ISSUE TITLE
`mexico_administracion_publica_federal_bulk` no longer available

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#972]

**Comment by yolile** [comment]
The same [happens](https://collect.data.open-contracting.org/logs/kingfisher/mexico_administracion_publica_federal_bulk/b8f2373064e411ed8e24a8a159689b50.log) in the registry server.

**Comment by jpmckinney** [comment]
@yolile Can you follow up with the publisher? I'm assuming their firewall is preventing the connection for whatever reason.

You tested from Hetzner servers. It doesn't work from Linode (CRM server) or Bytemark (DRT) either.

**Comment by yolile** [comment]
Yeap, I've already reported the issue to them and asked them to check their firewall rules.

**Comment by yolile** [comment]
Update: now the publication is entirely down (for everyone)

**Comment by yolile** [comment]
It is working again and also on our servers (outside Mexico)
