### ISSUE TITLE
dominican_republic_bulk is no longer working (2020)

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#988]
we need to use https://datosabiertos.dgcp.gob.do/opendata/estandar-mundial-ocds 
But they are not updating the files since 2020

**Comment by jpmckinney** [comment]
If they continue to be out-of-date, we can add a note to the docstring, to help users decide between this and _api.

**Comment by jpmckinney** [comment]
Maybe we add this to the "Broken spiders"?
