### ISSUE TITLE
Germany Bekanntmachungsservice: OpenData API

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-collect#992]
**Links to bulk download and/or API documentation**
https://www.oeffentlichevergabe.de/documentation/swagger-ui/opendata/index.html#/

**Links to bulk download and/or API endpoints**
https://www.oeffentlichevergabe.de/documentation/swagger-ui/opendata/index.html#/opendata/getExportAsEforms

**Priority**
anytime

**Data structure**
A lot of empty fields 

**Publication format**
Zip files with OCDS releases inside

*If the publication passes the [basic criteria](https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria), please follow the steps described at the [process note](https://docs.google.com/document/d/12d61HXZaD3wBYN479ShfZmc0xW29fJvmGNhkyf4xUhg/edit#heading=h.2fhb7gu8ein9).*

cc @ndrhzn

**Comment by yolile** [comment]
The publisher is The Procurement Office of the Federal Ministry of the Interior (BMI). 
The spider's name could therefore be `germany_bmi`  @jpmckinney any thoughts?

**Comment by jpmckinney** [comment]
(Re-reading https://kingfisher-collect.readthedocs.io/en/latest/contributing/index.html#choose-a-spider-name)

Are there other federal level publishers in Germany? If so, then yes, germany_bmi sounds good.

**Comment by yolile** [comment]
Their [website](https://www.oeffentlichevergabe.de/ui/en/home) says, "Welcome to the Publication Service, the **central** portal for searching for notices of public contracting authorities **from the Federal Government, the Länder and local authorities**!"

So I guess they are the only ones, and we can name it "`germany`"

**Comment by jpmckinney** [comment]
Sounds good!
